"""Type stubs for nexus_fast — Rust-accelerated PyO3 extension module.

Auto-generated from rust/nexus_pyo3/src/*.rs exports.
Keep in sync when adding new #[pyfunction] or #[pyclass] exports.
"""

from typing import Any

# ---------------------------------------------------------------------------
# Path utilities (path_utils.rs)
# ---------------------------------------------------------------------------

def split_path(path: str) -> list[str]: ...
def get_parent(path: str) -> str | None: ...
def get_ancestors(path: str) -> list[str]: ...
def get_parent_chain(path: str) -> list[tuple[str, str]]: ...
def parent_path(path: str) -> str | None: ...
def validate_path(path: str, allow_root: bool = False) -> str: ...
def normalize_path(path: str) -> str: ...
def path_matches_pattern(path: str, pattern: str) -> bool: ...
def unscope_internal_path(path: str) -> str: ...
def canonicalize_path(path: str, zone_id: str = "root") -> str: ...
def extract_zone_id(canonical_path: str) -> tuple[str, str]: ...

# ---------------------------------------------------------------------------
# Path prefix matching (prefix.rs)
# ---------------------------------------------------------------------------

def any_path_starts_with(paths: list[str], prefix: str) -> bool: ...
def batch_prefix_check(paths: list[str], prefixes: list[str]) -> list[bool]: ...
def filter_paths_by_prefix(paths: list[str], prefix: str) -> list[str]: ...

# ---------------------------------------------------------------------------
# Hash (hash.rs)
# ---------------------------------------------------------------------------

def hash_content_py(content: bytes) -> str: ...
def hash_content_smart_py(content: bytes) -> str: ...
def hash_bytes(data: bytes) -> str: ...

# ---------------------------------------------------------------------------
# Search (search.rs)
# ---------------------------------------------------------------------------

def grep_bulk(
    pattern: str,
    file_contents: dict[str, Any],
    ignore_case: bool = False,
    max_results: int = 1000,
) -> list[dict[str, Any]]: ...
def grep_files_mmap(
    pattern: str,
    file_paths: list[str],
    ignore_case: bool = False,
    max_results: int = 1000,
) -> list[dict[str, Any]]: ...

# ---------------------------------------------------------------------------
# Glob (glob.rs)
# ---------------------------------------------------------------------------

def glob_match_bulk(patterns: list[str], paths: list[str]) -> list[str]: ...
def filter_paths(paths: list[str], exclude_patterns: list[str]) -> list[str]: ...

# ---------------------------------------------------------------------------
# File I/O (io.rs)
# ---------------------------------------------------------------------------

def read_file(path: str) -> bytes | None: ...
def read_files_bulk(paths: list[str]) -> dict[str, bytes]: ...

# ---------------------------------------------------------------------------
# ReBAC (rebac.rs)
# ---------------------------------------------------------------------------

def compute_permissions_bulk(
    checks: list[Any],
    tuples: list[Any],
    namespace_configs: dict[str, Any],
    tuple_version: int = 0,
) -> dict[Any, bool]: ...
def compute_permission_single(
    subject_type: str,
    subject_id: str,
    permission: str,
    object_type: str,
    object_id: str,
    tuples: list[Any],
    namespace_configs: dict[str, Any],
) -> bool: ...
def expand_subjects(
    permission: str,
    object_type: str,
    object_id: str,
    tuples: list[Any],
    namespace_configs: dict[str, Any],
) -> list[tuple[str, str]]: ...
def list_objects_for_subject(
    subject_type: str,
    subject_id: str,
    permission: str,
    object_type: str,
    tuples: list[Any],
    namespace_configs: dict[str, Any],
    path_prefix: str | None = None,
    limit: int = 1000,
    offset: int = 0,
) -> list[tuple[str, str]]: ...

# ---------------------------------------------------------------------------
# Tiger Cache Bitmap (bitmap.rs)
# ---------------------------------------------------------------------------

def filter_paths_with_tiger_cache(path_int_ids: list[int], bitmap_bytes: bytes) -> list[int]: ...
def filter_paths_with_tiger_cache_parallel(
    path_int_ids: list[int], bitmap_bytes: bytes
) -> list[int]: ...
def intersect_paths_with_tiger_cache(path_int_ids: list[int], bitmap_bytes: bytes) -> list[int]: ...
def any_path_accessible_tiger_cache(path_int_ids: list[int], bitmap_bytes: bytes) -> bool: ...
def tiger_cache_bitmap_stats(bitmap_bytes: bytes) -> dict[str, Any]: ...

# ---------------------------------------------------------------------------
# SIMD vector similarity (simd.rs)
# ---------------------------------------------------------------------------

def cosine_similarity_f32(a: list[float], b: list[float]) -> float: ...
def dot_product_f32(a: list[float], b: list[float]) -> float: ...
def euclidean_sq_f32(a: list[float], b: list[float]) -> float: ...
def batch_cosine_similarity_f32(query: list[float], vectors: list[list[float]]) -> list[float]: ...
def top_k_similar_f32(
    query: list[float], vectors: list[list[float]], k: int
) -> list[tuple[int, float]]: ...
def cosine_similarity_i8(a: list[int], b: list[int]) -> float: ...
def batch_cosine_similarity_i8(query: list[int], vectors: list[list[int]]) -> list[float]: ...
def top_k_similar_i8(
    query: list[int], vectors: list[list[int]], k: int
) -> list[tuple[int, float]]: ...

# ---------------------------------------------------------------------------
# Trigram Index (trigram.rs)
# ---------------------------------------------------------------------------

def build_trigram_index(file_paths: list[str], output_path: str) -> None: ...
def build_trigram_index_from_entries(
    entries: list[tuple[str, bytes]], output_path: str
) -> None: ...
def trigram_grep(
    index_path: str,
    pattern: str,
    ignore_case: bool = False,
    max_results: int = 1000,
) -> list[dict[str, Any]]: ...
def trigram_search_candidates(
    index_path: str, pattern: str, ignore_case: bool = False
) -> list[str]: ...
def trigram_index_stats(index_path: str) -> dict[str, Any]: ...
def invalidate_trigram_cache(index_path: str) -> None: ...

# ---------------------------------------------------------------------------
# Classes
# ---------------------------------------------------------------------------

class BloomFilter:
    def __init__(self, expected_items: int = 100000, fp_rate: float = 0.01) -> None: ...
    def add(self, key: str) -> None: ...
    def add_bulk(self, keys: list[str]) -> None: ...
    def might_exist(self, key: str) -> bool: ...
    def check_bulk(self, keys: list[str]) -> list[bool]: ...
    def clear(self) -> None: ...
    @property
    def capacity(self) -> int: ...
    @property
    def fp_rate(self) -> float: ...
    @property
    def memory_bytes(self) -> int: ...

class L1MetadataCache:
    def __init__(self, max_entries: int = 100000, default_ttl: int = 300) -> None: ...
    def put(
        self,
        key: str,
        path_id: str,
        content_hash: str,
        disk_path: str,
        original_size: int,
        ttl_seconds: int = 0,
        is_text: bool = True,
        zone_id: str = "default",
    ) -> None: ...
    def get(self, key: str) -> tuple[str, str, str, int, bool, bool] | None: ...
    def get_content(self, key: str) -> tuple[bytes, str, bool] | None: ...
    def remove(self, key: str) -> bool: ...
    def remove_prefix(self, prefix: str) -> int: ...
    def clear(self) -> None: ...
    def stats(self) -> dict[str, Any]: ...
    def is_empty(self) -> bool: ...
    @property
    def len(self) -> int: ...
    @property
    def memory_bytes(self) -> int: ...

class VFSLockManager:
    def __init__(self) -> None: ...
    def acquire(self, path: str, mode: str, timeout_ms: int = 0) -> int: ...
    def release(self, handle: int) -> bool: ...
    def is_locked(self, path: str) -> bool: ...
    def holders(self, path: str) -> dict[str, Any] | None: ...
    def stats(self) -> dict[str, Any]: ...
    @property
    def active_locks(self) -> int: ...
    @property
    def active_handles(self) -> int: ...

class RingBufferCore:
    def __init__(self, capacity: int) -> None: ...
    def push(self, data: bytes) -> int: ...
    def push_u64(self, value: int) -> int: ...
    def pop(self) -> bytes: ...
    def pop_u64(self) -> int: ...
    def peek(self) -> bytes: ...
    def peek_all(self) -> list[bytes]: ...
    def close(self) -> None: ...
    def is_full(self) -> bool: ...
    def is_empty(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    def stats(self) -> dict[str, Any]: ...

class StreamBufferCore:
    def __init__(self, capacity: int) -> None: ...
    def push(self, data: bytes) -> int: ...
    def read_at(self, byte_offset: int) -> bytes: ...
    def read_batch(self, byte_offset: int, count: int) -> tuple[list[bytes], int]: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def tail(self) -> int: ...
    def stats(self) -> dict[str, Any]: ...

class SharedRingBufferCore:
    @staticmethod
    def create(capacity: int) -> tuple[SharedRingBufferCore, str, int, int]: ...
    @staticmethod
    def attach(
        shm_path: str, notify_data_wr: int, notify_space_wr: int
    ) -> SharedRingBufferCore: ...
    def push(self, data: bytes) -> int: ...
    def pop(self) -> bytes: ...
    def close(self) -> None: ...
    def cleanup(self) -> None: ...
    def is_full(self) -> bool: ...
    def is_empty(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    def stats(self) -> dict[str, Any]: ...

class SharedStreamBufferCore:
    @staticmethod
    def create(capacity: int) -> tuple[SharedStreamBufferCore, str, int]: ...
    @staticmethod
    def attach(shm_path: str, notify_data_wr: int) -> SharedStreamBufferCore: ...
    def push(self, data: bytes) -> int: ...
    def read_at(self, byte_offset: int) -> bytes: ...
    def read_batch(self, byte_offset: int, count: int) -> tuple[list[bytes], int]: ...
    def close(self) -> None: ...
    def cleanup(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def tail(self) -> int: ...
    def stats(self) -> dict[str, Any]: ...

class VFSSemaphore:
    def __init__(self) -> None: ...
    def acquire(
        self, name: str, max_holders: int, ttl_ms: int, timeout_ms: int = ...
    ) -> str | None: ...
    def release(self, name: str, holder_id: str) -> bool: ...
    def get_holders(self, name: str) -> list[str] | None: ...
    def sem_stats(self) -> dict[str, Any]: ...

class PathTrie:
    def __init__(self) -> None: ...
    def register(self, pattern: str, resolver_idx: int) -> None: ...
    def unregister(self, resolver_idx: int) -> bool: ...
    def lookup(self, path: str) -> int | None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class HookRegistry:
    def __init__(self) -> None: ...
    def register(
        self, op: str, hook: Any, *, has_pre: bool = ..., is_async_post: bool = ..., name: str = ...
    ) -> None: ...
    def unregister(self, op: str, hook: Any) -> bool: ...
    def get_pre_hooks(self, op: str) -> list[Any]: ...
    def get_post_hooks(self, op: str) -> list[Any]: ...
    def get_all_hooks(self, op: str) -> list[Any]: ...
    def count(self, op: str) -> int: ...

class ObserverRegistry:
    def __init__(self) -> None: ...
    def register(self, obs: Any, event_mask: int) -> None: ...
    def unregister(self, obs: Any) -> bool: ...
    def get_matching(self, event_type_bit: int) -> list[Any]: ...

class VolumeEngine:
    def __init__(self, root_dir: str) -> None: ...
    def write_blob(self, content_hash: str, data: bytes) -> str: ...
    def read_blob(self, content_hash: str) -> bytes | None: ...
    def delete_blob(self, content_hash: str) -> bool: ...
    def blob_exists(self, content_hash: str) -> bool: ...
    def blob_path(self, content_hash: str) -> str: ...

class RustDCache:
    def __init__(self) -> None: ...
    def put(
        self,
        path: str,
        backend_name: str,
        physical_path: str,
        size: int,
        entry_type: int,
        version: int = 1,
        etag: str | None = None,
        zone_id: str | None = None,
    ) -> None: ...
    def get(self, path: str) -> tuple[str, str, int] | None: ...
    def get_full(self, path: str) -> dict[str, Any] | None: ...
    def evict(self, path: str) -> bool: ...
    def evict_prefix(self, prefix: str) -> int: ...
    def contains(self, path: str) -> bool: ...
    def stats(self) -> dict[str, Any]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class RustPathRouter:
    def __init__(self) -> None: ...
    def add_mount(
        self,
        mount_point: str,
        zone_id: str,
        readonly: bool,
        admin_only: bool,
        io_profile: str,
        backend_name: str = "",
        local_root: str | None = None,
        fsync: bool = False,
        backend: Any = None,
    ) -> None: ...
    def remove_mount(self, mount_point: str, zone_id: str) -> bool: ...
    def route(
        self, path: str, zone_id: str, is_admin: bool, check_write: bool
    ) -> RustRouteResult: ...
    def has_mount(self, mount_point: str, zone_id: str) -> bool: ...
    def get_mount_points(self) -> list[str]: ...
    @staticmethod
    def canonicalize(path: str, zone_id: str) -> str: ...
    @staticmethod
    def strip_zone(canonical_path: str, zone_id: str) -> str: ...
    @staticmethod
    def extract_zone(canonical_path: str) -> tuple[str, str]: ...

class RustRouteResult:
    @property
    def mount_point(self) -> str: ...
    @property
    def backend_path(self) -> str: ...
    @property
    def readonly(self) -> bool: ...
    @property
    def io_profile(self) -> str: ...

class ReadPlan:
    action: int
    mount_point: str
    backend_path: str
    etag: str | None
    backend_name: str
    readonly: bool
    io_profile: str
    entry_type: int
    validated_path: str
    resolver_idx: int
    error_msg: str | None

class WritePlan:
    action: int
    mount_point: str
    backend_path: str
    etag: str | None
    backend_name: str
    readonly: bool
    io_profile: str
    entry_type: int
    validated_path: str
    resolver_idx: int
    error_msg: str | None
    version: int

class SyscallEngine:
    def __init__(
        self,
        dcache: RustDCache,
        router: RustPathRouter,
        trie: PathTrie,
        vfs_lock: VFSLockManager | None = None,
    ) -> None: ...
    def plan_read(self, path: str, zone_id: str, is_admin: bool) -> ReadPlan: ...
    def plan_write(self, path: str, zone_id: str, is_admin: bool) -> WritePlan: ...
    def sys_read(self, path: str, zone_id: str, is_admin: bool) -> bytes | None: ...
    def sys_write(self, path: str, zone_id: str, content: bytes, is_admin: bool) -> str | None: ...
    def set_hook_count(self, op: str, count: int) -> None: ...
    def __repr__(self) -> str: ...
