name: auto-tag-documents
description: Automatically tag documents based on content
version: 1.0

triggers:
  - type: file_write
    pattern: /workspace/**/*.{pdf,txt,md}

actions:
  - name: analyze_content
    type: llm
    model: claude-sonnet-4
    prompt: |
      Analyze this document and suggest relevant tags.
      Return a JSON array of tags (5-10 tags).
      Tags should be lowercase, single words or short phrases.

      Example: ["finance", "quarterly-report", "2024", "revenue"]
    output_format: json

  - name: apply_tags
    type: tag
    tags: "{analyze_content_output}"

  - name: add_metadata
    type: metadata
    metadata:
      auto_tagged: "true"
      tagged_at: "{timestamp}"
      model: "claude-sonnet-4"
