name: process-invoices
description: Auto-process invoices from inbox
version: 1.0

triggers:
  - type: file_write
    pattern: /inbox/invoices/**/*.pdf

actions:
  - name: parse_invoice
    type: parse
    parser: invoice

  - name: extract_metadata
    type: llm
    model: claude-sonnet-4
    prompt: |
      Extract from this invoice:
      - Invoice number
      - Amount
      - Date
      - Vendor name
    output_format: json

  - name: tag_document
    type: tag
    tags:
      - invoice
      - "vendor:{vendor_name}"
      - "year:{date.year}"

  - name: archive
    type: move
    destination: /archives/invoices/{year}/{vendor_name}/
    create_parents: true

  - name: notify
    type: webhook
    url: https://accounting.example.com/api/invoice-received
    method: POST
    body:
      invoice_number: "{invoice_number}"
      amount: "{amount}"
