# This is a config for E2B sandbox template.
# You can use template ID (irqihyk3wigfmup097s8) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("irqihyk3wigfmup097s8") # Sync sandbox
# sandbox = await AsyncSandbox.create("irqihyk3wigfmup097s8") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('irqihyk3wigfmup097s8')

team_id = "c95e0b17-985d-4f1c-88ef-858e33bf5b8b"
dockerfile = "e2b.Dockerfile"
template_id = "irqihyk3wigfmup097s8"
