{{- if or (and .Values.postgres.internal.enabled (not .Values.postgres.auth.existingSecret)) (and (not .Values.postgres.internal.enabled) (not .Values.postgres.external.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-hub.postgresSecretName" . }}
  labels:
    {{- include "nexus-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  {{ include "nexus-hub.postgresPasswordKey" . }}: {{- if .Values.postgres.internal.enabled }} {{ .Values.postgres.auth.password | quote }}{{- else }} {{ required "postgres.external.password is required when postgres.internal.enabled=false and postgres.external.existingSecret is not set" .Values.postgres.external.password | quote }}{{- end }}
{{- end }}
