# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nexus.a2a import a2a_pb2 as nexus_dot_a2a_dot_a2a__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus/a2a/a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2AServiceStub(object):
    """=== Service ===

    A2AService provides the gRPC transport binding for the A2A protocol.

    All RPCs are semantically equivalent to their JSON-RPC counterparts
    (tasks/send, tasks/sendSubscribe, tasks/get, tasks/cancel, tasks/resubscribe).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/nexus.a2a.A2AService/SendMessage',
                request_serializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendStreamingMessage = channel.unary_stream(
                '/nexus.a2a.A2AService/SendStreamingMessage',
                request_serializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=nexus_dot_a2a_dot_a2a__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/nexus.a2a.A2AService/GetTask',
                request_serializer=nexus_dot_a2a_dot_a2a__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=nexus_dot_a2a_dot_a2a__pb2.Task.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/nexus.a2a.A2AService/CancelTask',
                request_serializer=nexus_dot_a2a_dot_a2a__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=nexus_dot_a2a_dot_a2a__pb2.Task.FromString,
                _registered_method=True)
        self.SubscribeToTask = channel.unary_stream(
                '/nexus.a2a.A2AService/SubscribeToTask',
                request_serializer=nexus_dot_a2a_dot_a2a__pb2.SubscribeToTaskRequest.SerializeToString,
                response_deserializer=nexus_dot_a2a_dot_a2a__pb2.StreamResponse.FromString,
                _registered_method=True)


class A2AServiceServicer(object):
    """=== Service ===

    A2AService provides the gRPC transport binding for the A2A protocol.

    All RPCs are semantically equivalent to their JSON-RPC counterparts
    (tasks/send, tasks/sendSubscribe, tasks/get, tasks/cancel, tasks/resubscribe).
    """

    def SendMessage(self, request, context):
        """SendMessage creates or continues a task with a user message.
        Equivalent to JSON-RPC method "tasks/send".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStreamingMessage(self, request, context):
        """SendStreamingMessage creates or continues a task, returning a stream
        of status and artifact updates.
        Equivalent to JSON-RPC method "tasks/sendSubscribe".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """GetTask retrieves a task by ID.
        Equivalent to JSON-RPC method "tasks/get".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """CancelTask transitions a task to the CANCELED state.
        Equivalent to JSON-RPC method "tasks/cancel".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToTask(self, request, context):
        """SubscribeToTask subscribes to updates for an existing task.
        Equivalent to JSON-RPC method "tasks/resubscribe".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.FromString,
                    response_serializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendStreamingMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendStreamingMessage,
                    request_deserializer=nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.FromString,
                    response_serializer=nexus_dot_a2a_dot_a2a__pb2.StreamResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=nexus_dot_a2a_dot_a2a__pb2.GetTaskRequest.FromString,
                    response_serializer=nexus_dot_a2a_dot_a2a__pb2.Task.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=nexus_dot_a2a_dot_a2a__pb2.CancelTaskRequest.FromString,
                    response_serializer=nexus_dot_a2a_dot_a2a__pb2.Task.SerializeToString,
            ),
            'SubscribeToTask': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToTask,
                    request_deserializer=nexus_dot_a2a_dot_a2a__pb2.SubscribeToTaskRequest.FromString,
                    response_serializer=nexus_dot_a2a_dot_a2a__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.a2a.A2AService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.a2a.A2AService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2AService(object):
    """=== Service ===

    A2AService provides the gRPC transport binding for the A2A protocol.

    All RPCs are semantically equivalent to their JSON-RPC counterparts
    (tasks/send, tasks/sendSubscribe, tasks/get, tasks/cancel, tasks/resubscribe).
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.a2a.A2AService/SendMessage',
            nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.SerializeToString,
            nexus_dot_a2a_dot_a2a__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStreamingMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nexus.a2a.A2AService/SendStreamingMessage',
            nexus_dot_a2a_dot_a2a__pb2.SendMessageRequest.SerializeToString,
            nexus_dot_a2a_dot_a2a__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.a2a.A2AService/GetTask',
            nexus_dot_a2a_dot_a2a__pb2.GetTaskRequest.SerializeToString,
            nexus_dot_a2a_dot_a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.a2a.A2AService/CancelTask',
            nexus_dot_a2a_dot_a2a__pb2.CancelTaskRequest.SerializeToString,
            nexus_dot_a2a_dot_a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nexus.a2a.A2AService/SubscribeToTask',
            nexus_dot_a2a_dot_a2a__pb2.SubscribeToTaskRequest.SerializeToString,
            nexus_dot_a2a_dot_a2a__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
