"""Auto-generated from proto/nexus/core/metadata.proto - DO NOT EDIT.

This module is generated by: python scripts/gen_metadata.py
SSOT: proto/nexus/core/metadata.proto

To modify FileMetadata:
  1. Edit proto/nexus/core/metadata.proto
  2. Run: python scripts/gen_metadata.py
  3. Never edit this file directly!

Contains:
  - FileMetadata: Core file metadata dataclass
  - DT_REG, DT_DIR, DT_MOUNT, DT_PIPE: Directory entry type constants
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from nexus.core._compact_generated import CompactFileMetadata


# DirEntryType (from proto/nexus/core/metadata.proto)
DT_REG = 0
DT_DIR = 1
DT_MOUNT = 2
DT_PIPE = 3


@dataclass(slots=True)
class FileMetadata:
    """File metadata information.

    Generated from: proto/nexus/core/metadata.proto
    """

    path: str
    backend_name: str
    physical_path: str
    size: int
    etag: str | None = None
    mime_type: str | None = None
    created_at: datetime | None = None
    modified_at: datetime | None = None
    version: int = 1
    zone_id: str | None = None
    created_by: str | None = None
    owner_id: str | None = None
    entry_type: int = 0
    target_zone_id: str | None = None
    i_links_count: int = 0

    @property
    def is_reg(self) -> bool:
        return self.entry_type == 0

    @property
    def is_dir(self) -> bool:
        return self.entry_type == 1

    @property
    def is_mount(self) -> bool:
        return self.entry_type == 2

    @property
    def is_pipe(self) -> bool:
        return self.entry_type == 3

    def validate(self) -> None:
        """Validate file metadata before database operations.

        Raises:
            ValidationError: If validation fails with clear message.
        """
        from nexus.contracts.exceptions import ValidationError

        if not self.path:
            raise ValidationError("path is required")

        if not self.path.startswith("/"):
            raise ValidationError(f"path must start with '/', got {self.path!r}", path=self.path)

        if "\x00" in self.path:
            raise ValidationError("path contains null bytes", path=self.path)

        # DT_PIPE inodes: in-memory ring buffer, no backend storage required
        if self.entry_type == 3:  # DT_PIPE
            return

        if not self.backend_name:
            raise ValidationError("backend_name is required", path=self.path)

        if not self.physical_path:
            raise ValidationError("physical_path is required", path=self.path)

        if self.size < 0:
            raise ValidationError(f"size cannot be negative, got {self.size}", path=self.path)

        if self.version < 1:
            raise ValidationError(f"version must be >= 1, got {self.version}", path=self.path)

    def to_compact(self) -> CompactFileMetadata:
        """Convert to memory-efficient CompactFileMetadata.

        Uses string interning to deduplicate path/hash strings across instances.
        Reduces memory from ~200-300 bytes to ~64-100 bytes per instance.

        Returns:
            CompactFileMetadata with interned strings and packed fields
        """
        from nexus.core._compact_generated import CompactFileMetadata

        return CompactFileMetadata.from_file_metadata(self)

    @classmethod
    def from_compact(cls, compact: CompactFileMetadata) -> FileMetadata:
        """Create FileMetadata from CompactFileMetadata.

        Resolves interned string IDs back to full strings.

        Args:
            compact: CompactFileMetadata instance

        Returns:
            Full FileMetadata object
        """
        return compact.to_file_metadata()
