"""Auto-generated RPC Param dataclasses — DO NOT EDIT MANUALLY.

Generated by ``scripts/generate_rpc_params.py`` from @rpc_expose method
signatures.  Re-run that script whenever you add or change an RPC method.

Manual overrides live in ``_rpc_param_overrides.py`` and are imported
after this module by ``protocol.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

__all__ = [
    "AccessShareLinkParams",
    "AceAddFeedbackParams",
    "AceCompleteTrajectoryParams",
    "AceCreatePlaybookParams",
    "AceGetEffectiveScoreParams",
    "AceGetPlaybookParams",
    "AceGetTrajectoryFeedbackParams",
    "AceLogTrajectoryStepParams",
    "AceMarkForRelearningParams",
    "AceQueryPlaybooksParams",
    "AceQueryTrajectoriesParams",
    "AceStartTrajectoryParams",
    "AddMountParams",
    "AgentHeartbeatParams",
    "AgentListByZoneParams",
    "AgentTransitionParams",
    "AppendParams",
    "BackfillDirectoryIndexParams",
    "CancelSyncJobParams",
    "CancelTaskParams",
    "CreateShareLinkParams",
    "DeleteAgentParams",
    "DeleteBulkParams",
    "DeleteConnectorParams",
    "DeleteSavedMountParams",
    "DeprovisionUserParams",
    "DiffVersionsParams",
    "EditParams",
    "ExistsBatchParams",
    "GetAgentParams",
    "GetEtagParams",
    "GetMemoryInfoParams",
    "GetMountParams",
    "GetShareLinkAccessLogsParams",
    "GetShareLinkParams",
    "GetSyncJobParams",
    "GetTaskParams",
    "GetTaskStatsParams",
    "GetTopLevelMountsParams",
    "GetVersionParams",
    "GetWorkspaceInfoParams",
    "GlobBatchParams",
    "GlobParams",
    "GrepParams",
    "HasMountParams",
    "ListAgentsParams",
    "ListConnectorsParams",
    "ListIncomingSharesParams",
    "ListMountsParams",
    "ListOutgoingSharesParams",
    "ListParams",
    "ListQueueTasksParams",
    "ListRegisteredMemoriesParams",
    "ListSavedMountsParams",
    "ListShareLinksParams",
    "ListSyncJobsParams",
    "ListVersionsParams",
    "ListWorkspacesParams",
    "LoadMountParams",
    "MCPConnectParams",
    "MCPListMountsParams",
    "MCPListToolsParams",
    "MCPMountParams",
    "MCPSyncParams",
    "MCPUnmountParams",
    "MakePrivateParams",
    "MakePublicParams",
    "MetadataBatchParams",
    "NamespaceDeleteParams",
    "NamespaceListParams",
    "OAuthListCredentialsParams",
    "OAuthListProvidersParams",
    "OAuthRevokeCredentialParams",
    "OAuthTestCredentialParams",
    "ProvisionUserParams",
    "ReadBulkParams",
    "RebacCheckParams",
    "RebacCreateParams",
    "RebacDeleteParams",
    "RebacExpandParams",
    "RebacExplainParams",
    "RebacListObjectsParams",
    "RebacListTuplesParams",
    "RegisterAgentParams",
    "RegisterMemoryParams",
    "RegisterWorkspaceParams",
    "RemoveMountParams",
    "RenameBulkParams",
    "RevokeShareByIdParams",
    "RevokeShareLinkParams",
    "RevokeShareParams",
    "RollbackParams",
    "SaveMountParams",
    "SemanticSearchIndexParams",
    "ShareWithUserParams",
    "SkillsDiscoverParams",
    "SkillsExportParams",
    "SkillsGetPromptContextParams",
    "SkillsImportParams",
    "SkillsLoadParams",
    "SkillsShareParams",
    "SkillsSubscribeParams",
    "SkillsUnshareParams",
    "SkillsUnsubscribeParams",
    "SkillsValidateZipParams",
    "SnapshotBeginParams",
    "SnapshotCommitParams",
    "SnapshotRollbackParams",
    "StatBulkParams",
    "StatParams",
    "SubmitTaskParams",
    "SyncMountAsyncParams",
    "SyncMountParams",
    "SysAccessParams",
    "SysIsDirectoryParams",
    "SysMkdirParams",
    "SysReaddirParams",
    "SysRenameParams",
    "SysRmdirParams",
    "SysStatParams",
    "SysUnlinkParams",
    "SysWriteParams",
    "UnregisterMemoryParams",
    "UnregisterWorkspaceParams",
    "UpdateAgentParams",
    "UpdateWorkspaceParams",
    "WorkspaceDiffParams",
    "WorkspaceLogParams",
    "WorkspaceRestoreParams",
    "WorkspaceSnapshotParams",
    "WriteBatchParams",
]


@dataclass
class AccessShareLinkParams:
    """Parameters for access_share_link(): Validate and access a shared resource via share link."""

    link_id: str
    password: str | None = None
    ip_address: str | None = None
    user_agent: str | None = None


@dataclass
class AceAddFeedbackParams:
    """Parameters for ace_add_feedback(): Add feedback to a completed trajectory."""

    trajectory_id: str
    feedback_type: str
    score: float | None = None
    source: str | None = None
    message: str | None = None
    metrics: dict | None = None
    context: dict | None = None


@dataclass
class AceCompleteTrajectoryParams:
    """Parameters for ace_complete_trajectory(): Complete a trajectory with outcome."""

    trajectory_id: str
    status: str
    success_score: float | None = None
    error_message: str | None = None
    context: dict | None = None


@dataclass
class AceCreatePlaybookParams:
    """Parameters for ace_create_playbook(): Create a new playbook."""

    name: str
    description: str | None = None
    scope: str = "agent"
    context: dict | None = None


@dataclass
class AceGetEffectiveScoreParams:
    """Parameters for ace_get_effective_score(): Get effective score for a trajectory."""

    trajectory_id: str
    strategy: str = "latest"
    context: dict | None = None


@dataclass
class AceGetPlaybookParams:
    """Parameters for ace_get_playbook(): Get playbook details."""

    playbook_id: str
    context: dict | None = None


@dataclass
class AceGetTrajectoryFeedbackParams:
    """Parameters for ace_get_trajectory_feedback(): Get all feedback for a trajectory."""

    trajectory_id: str
    context: dict | None = None


@dataclass
class AceLogTrajectoryStepParams:
    """Parameters for ace_log_trajectory_step(): Log a step in an execution trajectory."""

    trajectory_id: str
    step_type: str
    description: str
    result: Any = None
    context: dict | None = None


@dataclass
class AceMarkForRelearningParams:
    """Parameters for ace_mark_for_relearning(): Mark trajectory for re-learning."""

    trajectory_id: str
    reason: str
    priority: int = 5
    context: dict | None = None


@dataclass
class AceQueryPlaybooksParams:
    """Parameters for ace_query_playbooks(): Query playbooks."""

    scope: str | None = None
    limit: int = 50
    context: dict | None = None


@dataclass
class AceQueryTrajectoriesParams:
    """Parameters for ace_query_trajectories(): Query execution trajectories."""

    task_type: str | None = None
    status: str | None = None
    limit: int = 50
    context: dict | None = None


@dataclass
class AceStartTrajectoryParams:
    """Parameters for ace_start_trajectory(): Start tracking a new execution trajectory for ACE learning."""

    task_description: str
    task_type: str | None = None
    context: dict | None = None


@dataclass
class AddMountParams:
    """Parameters for add_mount(): Add a dynamic backend mount to the filesystem."""

    mount_point: str
    backend_type: str
    backend_config: dict[str, Any]
    readonly: bool = False
    io_profile: str = "balanced"


@dataclass
class AgentHeartbeatParams:
    """Parameters for agent_heartbeat(): Record a heartbeat for an active agent."""

    agent_id: str


@dataclass
class AgentListByZoneParams:
    """Parameters for agent_list_by_zone(): List agents in a zone, optionally filtered by state."""

    zone_id: str
    state: str | None = None


@dataclass
class AgentTransitionParams:
    """Parameters for agent_transition(): Transition an agent's lifecycle state with optimistic locking."""

    agent_id: str
    target_state: str
    expected_generation: int | None = None


@dataclass
class AppendParams:
    """Parameters for append(): Append content to an existing file or create a new file if it doesn't exist."""

    path: str
    content: bytes | str
    if_match: str | None = None
    force: bool = False


@dataclass
class BackfillDirectoryIndexParams:
    """Parameters for backfill_directory_index(): Backfill sparse directory index from existing files."""

    prefix: str = "/"
    zone_id: str | None = None


@dataclass
class CancelSyncJobParams:
    """Parameters for cancel_sync_job(): Cancel a running sync job."""

    job_id: str


@dataclass
class CancelTaskParams:
    """Parameters for cancel_task(): Cancel a pending or running task."""

    task_id: int


@dataclass
class CreateShareLinkParams:
    """Parameters for create_share_link(): Create a shareable link for a file or directory."""

    path: str
    permission_level: str = "viewer"
    expires_in_hours: int | None = None
    max_access_count: int | None = None
    password: str | None = None


@dataclass
class DeleteAgentParams:
    """Parameters for delete_agent(): Delete a registered agent (v0.5.0)."""

    agent_id: str


@dataclass
class DeleteBulkParams:
    """Parameters for delete_bulk(): Delete multiple files or directories in a single operation."""

    paths: list[str]
    recursive: bool = False


@dataclass
class DeleteConnectorParams:
    """Parameters for delete_connector(): Delete a connector completely with bundled operations."""

    mount_point: str
    revoke_oauth: bool = False
    provider: str | None = None
    user_email: str | None = None


@dataclass
class DeleteSavedMountParams:
    """Parameters for delete_saved_mount(): Delete a saved mount configuration from the database."""

    mount_point: str


@dataclass
class DeprovisionUserParams:
    """Parameters for deprovision_user(): Deprovision a user and remove all their resources."""

    user_id: str
    zone_id: str | None = None
    delete_user_record: bool = False
    force: bool = False


@dataclass
class DiffVersionsParams:
    """Parameters for diff_versions(): Compare two versions of a file."""

    path: str
    v1: int
    v2: int
    mode: str = "metadata"


@dataclass
class EditParams:
    """Parameters for edit(): Apply surgical search/replace edits to a file."""

    path: str
    edits: list[tuple[str, str]] | list[dict[str, Any]] | list[Any]
    if_match: str | None = None
    fuzzy_threshold: float = 0.85
    preview: bool = False

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.edits, list):
            object.__setattr__(self, "edits", tuple(self.edits))


@dataclass
class ExistsBatchParams:
    """Parameters for exists_batch(): Check existence of multiple paths in a single call (Issue #859)."""

    paths: list[str]


@dataclass
class GetAgentParams:
    """Parameters for get_agent(): Get information about a registered agent (v0.5.0)."""

    agent_id: str


@dataclass
class GetEtagParams:
    """Parameters for get_etag(): Get content hash for HTTP If-None-Match checks."""

    path: str


@dataclass
class GetMemoryInfoParams:
    """Parameters for get_memory_info(): Get information about a registered memory."""

    path: str


@dataclass
class GetMountParams:
    """Parameters for get_mount(): Get details about a specific mount."""

    mount_point: str


@dataclass
class GetShareLinkParams:
    """Parameters for get_share_link(): Get details of a share link."""

    link_id: str


@dataclass
class GetShareLinkAccessLogsParams:
    """Parameters for get_share_link_access_logs(): Get access logs for a share link."""

    link_id: str
    limit: int = 100


@dataclass
class GetSyncJobParams:
    """Parameters for get_sync_job(): Get the status and progress of a sync job."""

    job_id: str


@dataclass
class GetTaskParams:
    """Parameters for get_task(): Get task status and details."""

    task_id: int


@dataclass
class GetTaskStatsParams:
    """Parameters for get_task_stats(): Get queue statistics."""

    pass


@dataclass
class GetTopLevelMountsParams:
    """Parameters for get_top_level_mounts(): Return top-level mount names visible to the current user."""

    pass


@dataclass
class GetVersionParams:
    """Parameters for get_version(): Get a specific version of a file."""

    path: str
    version: int


@dataclass
class GetWorkspaceInfoParams:
    """Parameters for get_workspace_info(): Get information about a registered workspace."""

    path: str


@dataclass
class GlobParams:
    """Parameters for glob(): Find files matching a glob pattern."""

    pattern: str
    path: str = "/"
    context: Any = None


@dataclass
class GlobBatchParams:
    """Parameters for glob_batch(): Execute multiple glob patterns in a single call (Issue #859)."""

    patterns: list[str]
    path: str = "/"
    context: Any = None


@dataclass
class GrepParams:
    """Parameters for grep(): Search file contents using regex patterns."""

    pattern: str
    path: str = "/"
    file_pattern: str | None = None
    ignore_case: bool = False
    max_results: int = 100
    search_mode: str = "auto"
    context: Any = None


@dataclass
class HasMountParams:
    """Parameters for has_mount(): Check if a mount exists at the given path."""

    mount_point: str


@dataclass
class ListParams:
    """Parameters for list(): List files in a directory."""

    path: str = "/"
    recursive: bool = True
    details: bool = False
    show_parsed: bool = True
    context: Any = None
    limit: int | None = None
    cursor: str | None = None


@dataclass
class ListAgentsParams:
    """Parameters for list_agents(): List all registered agents (v0.5.0)."""

    pass


@dataclass
class ListConnectorsParams:
    """Parameters for list_connectors(): List all available connector types that can be used with add_mount()."""

    category: str | None = None


@dataclass
class ListIncomingSharesParams:
    """Parameters for list_incoming_shares(): List all resources shared with a subject."""

    subject: tuple[str, str]
    object_type: str = "file"
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))


@dataclass
class ListMountsParams:
    """Parameters for list_mounts(): List all active backend mounts that the user has permission to access."""

    pass


@dataclass
class ListOutgoingSharesParams:
    """Parameters for list_outgoing_shares(): List all shares granted on a resource."""

    resource: tuple[str, str]
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.resource, list):
            object.__setattr__(self, "resource", tuple(self.resource))


@dataclass
class ListQueueTasksParams:
    """Parameters for list_queue_tasks(): List tasks with optional filters."""

    task_type: str | None = None
    status: int | None = None
    limit: int = 50
    offset: int = 0


@dataclass
class ListRegisteredMemoriesParams:
    """Parameters for list_registered_memories(): List all registered memory paths."""

    pass


@dataclass
class ListSavedMountsParams:
    """Parameters for list_saved_mounts(): List mount configurations saved in the database."""

    owner_user_id: str | None = None
    zone_id: str | None = None


@dataclass
class ListShareLinksParams:
    """Parameters for list_share_links(): List share links created by the current user."""

    path: str | None = None
    include_revoked: bool = False
    include_expired: bool = False


@dataclass
class ListSyncJobsParams:
    """Parameters for list_sync_jobs(): List sync jobs with optional filters."""

    mount_point: str | None = None
    status: str | None = None
    limit: int = 50


@dataclass
class ListVersionsParams:
    """Parameters for list_versions(): List all versions of a file."""

    path: str


@dataclass
class ListWorkspacesParams:
    """Parameters for list_workspaces(): List all registered workspaces for the current user."""

    context: Any | None = None


@dataclass
class LoadMountParams:
    """Parameters for load_mount(): Load a saved mount configuration and activate it."""

    mount_point: str


@dataclass
class MakePrivateParams:
    """Parameters for make_private(): Remove public (wildcard) access from a resource."""

    resource: tuple[str, str]
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.resource, list):
            object.__setattr__(self, "resource", tuple(self.resource))


@dataclass
class MakePublicParams:
    """Parameters for make_public(): Make a resource publicly accessible (wildcard viewer)."""

    resource: tuple[str, str]
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.resource, list):
            object.__setattr__(self, "resource", tuple(self.resource))


@dataclass
class MCPConnectParams:
    """Parameters for mcp_connect(): Connect to an MCP provider using Klavis hosted OAuth."""

    provider: str
    redirect_url: str | None = None


@dataclass
class MCPListMountsParams:
    """Parameters for mcp_list_mounts(): List MCP server mounts."""

    tier: str | None = None
    include_unmounted: bool = True


@dataclass
class MCPListToolsParams:
    """Parameters for mcp_list_tools(): List tools from a specific MCP mount."""

    name: str


@dataclass
class MCPMountParams:
    """Parameters for mcp_mount(): Mount an MCP server."""

    name: str
    transport: str | None = None
    command: str | None = None
    url: str | None = None
    args: list[str] | None = None
    env: dict[str, str] | None = None
    headers: dict[str, str] | None = None
    description: str | None = None
    tier: str = "system"


@dataclass
class MCPSyncParams:
    """Parameters for mcp_sync(): Sync/refresh tools from an MCP server."""

    name: str


@dataclass
class MCPUnmountParams:
    """Parameters for mcp_unmount(): Unmount an MCP server."""

    name: str


@dataclass
class MetadataBatchParams:
    """Parameters for metadata_batch(): Get metadata for multiple paths in a single call (Issue #859)."""

    paths: list[str]


@dataclass
class NamespaceDeleteParams:
    """Parameters for namespace_delete(): Delete all tuples for a namespace's object type."""

    object_type: str
    zone_id: str | None = None


@dataclass
class NamespaceListParams:
    """Parameters for namespace_list(): List all registered namespace configurations."""

    pass


@dataclass
class OAuthListCredentialsParams:
    """Parameters for oauth_list_credentials(): List all OAuth credentials for the current user."""

    provider: str | None = None
    include_revoked: bool = False


@dataclass
class OAuthListProvidersParams:
    """Parameters for oauth_list_providers(): List all available OAuth providers from configuration."""

    pass


@dataclass
class OAuthRevokeCredentialParams:
    """Parameters for oauth_revoke_credential(): Revoke an OAuth credential."""

    provider: str
    user_email: str


@dataclass
class OAuthTestCredentialParams:
    """Parameters for oauth_test_credential(): Test if an OAuth credential is valid and can be refreshed."""

    provider: str
    user_email: str


@dataclass
class ProvisionUserParams:
    """Parameters for provision_user(): Provision a new user with all default resources (Issue #820)."""

    user_id: str
    email: str
    display_name: str | None = None
    zone_id: str | None = None
    zone_name: str | None = None
    create_api_key: bool = True
    api_key_name: str | None = None
    api_key_expires_at: str | None = None
    create_agents: bool = True
    import_skills: bool = True


@dataclass
class ReadBulkParams:
    """Parameters for read_bulk(): Read multiple files in a single RPC call for improved performance."""

    paths: list[str]
    return_metadata: bool = False
    skip_errors: bool = True


@dataclass
class RebacCheckParams:
    """Parameters for rebac_check(): Check if subject has permission on object (Issue #1081)."""

    subject: tuple[str, str]
    permission: str
    object: tuple[str, str]
    context: Any = None
    zone_id: str | None = None
    consistency_mode: str | None = None
    min_revision: int | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))
        if isinstance(self.object, list):
            object.__setattr__(self, "object", tuple(self.object))


@dataclass
class RebacCreateParams:
    """Parameters for rebac_create(): Create a ReBAC relationship tuple (Issue #1081)."""

    subject: tuple[str, str]
    relation: str
    object: tuple[str, str]
    expires_at: str | None = None
    zone_id: str | None = None
    context: Any = None
    column_config: dict[str, Any] | None = None
    conditions: dict[str, Any] | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))
        if isinstance(self.object, list):
            object.__setattr__(self, "object", tuple(self.object))


@dataclass
class RebacDeleteParams:
    """Parameters for rebac_delete(): Delete a relationship tuple by ID."""

    tuple_id: str


@dataclass
class RebacExpandParams:
    """Parameters for rebac_expand(): Find all subjects that have a permission on an object."""

    permission: str
    object: tuple[str, str]
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.object, list):
            object.__setattr__(self, "object", tuple(self.object))


@dataclass
class RebacExplainParams:
    """Parameters for rebac_explain(): Explain why a subject has or doesn't have permission."""

    subject: tuple[str, str]
    permission: str
    object: tuple[str, str]
    zone_id: str | None = None
    context: Any = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))
        if isinstance(self.object, list):
            object.__setattr__(self, "object", tuple(self.object))


@dataclass
class RebacListObjectsParams:
    """Parameters for rebac_list_objects(): List objects that a subject has a given relation to."""

    relation: str
    subject: tuple[str, str]
    zone_id: str | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))


@dataclass
class RebacListTuplesParams:
    """Parameters for rebac_list_tuples(): List relationship tuples with optional filters."""

    subject: tuple[str, str] | None = None
    relation: str | None = None
    object: tuple[str, str] | None = None
    relation_in: list[str] | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))
        if isinstance(self.object, list):
            object.__setattr__(self, "object", tuple(self.object))


@dataclass
class RegisterAgentParams:
    """Parameters for register_agent(): Register an AI agent (v0.5.0)."""

    agent_id: str
    name: str
    description: str | None = None
    generate_api_key: bool = False
    metadata: dict | None = None
    capabilities: list[str] | None = None
    context: dict | None = None


@dataclass
class RegisterMemoryParams:
    """Parameters for register_memory(): Register a directory as a memory."""

    path: str
    name: str | None = None
    description: str | None = None
    created_by: str | None = None
    tags: list[str] | None = None
    metadata: dict[str, Any] | None = None
    session_id: str | None = None
    ttl: str | None = None
    context: Any | None = None


@dataclass
class RegisterWorkspaceParams:
    """Parameters for register_workspace(): Register a directory as a workspace."""

    path: str
    name: str | None = None
    description: str | None = None
    created_by: str | None = None
    tags: list[str] | None = None
    metadata: dict[str, Any] | None = None
    session_id: str | None = None
    ttl: str | None = None
    context: Any | None = None


@dataclass
class RemoveMountParams:
    """Parameters for remove_mount(): Remove a backend mount from the filesystem."""

    mount_point: str


@dataclass
class RenameBulkParams:
    """Parameters for rename_bulk(): Rename/move multiple files in a single operation."""

    renames: list[tuple[str, str]]

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.renames, list):
            object.__setattr__(self, "renames", tuple(self.renames))


@dataclass
class RevokeShareParams:
    """Parameters for revoke_share(): Revoke a specific share (find and delete the matching tuple)."""

    resource: tuple[str, str]
    target: tuple[str, str]
    permission: str = "viewer"
    zone_id: str | None = None
    context: Any = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.resource, list):
            object.__setattr__(self, "resource", tuple(self.resource))
        if isinstance(self.target, list):
            object.__setattr__(self, "target", tuple(self.target))


@dataclass
class RevokeShareByIdParams:
    """Parameters for revoke_share_by_id(): Revoke a share by its tuple ID."""

    tuple_id: str
    context: Any = None


@dataclass
class RevokeShareLinkParams:
    """Parameters for revoke_share_link(): Revoke a share link, immediately disabling access."""

    link_id: str


@dataclass
class RollbackParams:
    """Parameters for rollback(): Rollback file to a previous version."""

    path: str
    version: int


@dataclass
class SaveMountParams:
    """Parameters for save_mount(): Save a mount configuration to the database for persistence."""

    mount_point: str
    backend_type: str
    backend_config: dict[str, Any]
    readonly: bool = False
    io_profile: str = "balanced"
    owner_user_id: str | None = None
    zone_id: str | None = None
    description: str | None = None


@dataclass
class SemanticSearchIndexParams:
    """Parameters for semantic_search_index(): Index documents for semantic search."""

    path: str = "/"
    recursive: bool = True


@dataclass
class ShareWithUserParams:
    """Parameters for share_with_user(): Share a resource with a specific user."""

    resource: tuple[str, str]
    target_user: str
    permission: str = "viewer"
    zone_id: str | None = None
    context: Any = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.resource, list):
            object.__setattr__(self, "resource", tuple(self.resource))


@dataclass
class SkillsDiscoverParams:
    """Parameters for skills_discover(): RPC wrapper for discover()."""

    filter: str = "all"
    context: Any | None = None


@dataclass
class SkillsExportParams:
    """Parameters for skills_export(): Export a skill to .skill (ZIP) format."""

    skill_path: str | None = None
    skill_name: str | None = None
    output_path: str | None = None
    format: str = "generic"
    include_dependencies: bool = False
    context: Any | None = None


@dataclass
class SkillsGetPromptContextParams:
    """Parameters for skills_get_prompt_context(): RPC wrapper for get_prompt_context()."""

    max_skills: int = 50
    context: Any | None = None


@dataclass
class SkillsImportParams:
    """Parameters for skills_import(): Import a skill from .skill (ZIP) format."""

    source_path: str | None = None
    zip_bytes: bytes | str | None = None
    zip_data: str | None = None
    target_path: str | None = None
    allow_overwrite: bool = False
    context: Any | None = None
    tier: str | None = None


@dataclass
class SkillsLoadParams:
    """Parameters for skills_load(): RPC wrapper for load()."""

    skill_path: str
    context: Any | None = None


@dataclass
class SkillsShareParams:
    """Parameters for skills_share(): RPC wrapper for share()."""

    skill_path: str
    share_with: str
    context: Any | None = None


@dataclass
class SkillsSubscribeParams:
    """Parameters for skills_subscribe(): RPC wrapper for subscribe()."""

    skill_path: str
    context: Any | None = None


@dataclass
class SkillsUnshareParams:
    """Parameters for skills_unshare(): RPC wrapper for unshare()."""

    skill_path: str
    unshare_from: str
    context: Any | None = None


@dataclass
class SkillsUnsubscribeParams:
    """Parameters for skills_unsubscribe(): RPC wrapper for unsubscribe()."""

    skill_path: str
    context: Any | None = None


@dataclass
class SkillsValidateZipParams:
    """Parameters for skills_validate_zip(): Validate a .skill (ZIP) package without importing it."""

    source_path: str | None = None
    zip_bytes: bytes | str | None = None
    zip_data: str | None = None
    context: Any | None = None


@dataclass
class SnapshotBeginParams:
    """Parameters for snapshot_begin(): Begin a transactional snapshot for the specified paths."""

    paths: list[str]
    agent_id: str | None = None
    zone_id: str = "root"


@dataclass
class SnapshotCommitParams:
    """Parameters for snapshot_commit(): Commit a snapshot — changes become permanent."""

    snapshot_id: str


@dataclass
class SnapshotRollbackParams:
    """Parameters for snapshot_rollback(): Rollback a snapshot — restore paths to pre-snapshot state."""

    snapshot_id: str


@dataclass
class StatParams:
    """Parameters for stat(): Get file metadata without reading the file content."""

    path: str


@dataclass
class StatBulkParams:
    """Parameters for stat_bulk(): Get metadata for multiple files in a single RPC call."""

    paths: list[str]
    skip_errors: bool = True


@dataclass
class SubmitTaskParams:
    """Parameters for submit_task(): Submit a task to the durable queue."""

    task_type: str
    params_json: str = "{}"
    priority: int = 2
    max_retries: int = 3


@dataclass
class SyncMountParams:
    """Parameters for sync_mount(): Sync metadata and content from connector backend(s) to Nexus database."""

    mount_point: str | None = None
    path: str | None = None
    recursive: bool = True
    dry_run: bool = False
    sync_content: bool = True
    include_patterns: list[str] | None = None
    exclude_patterns: list[str] | None = None
    generate_embeddings: bool = False
    full_sync: bool = False


@dataclass
class SyncMountAsyncParams:
    """Parameters for sync_mount_async(): Start an async sync job for a mount point."""

    mount_point: str
    path: str | None = None
    recursive: bool = True
    dry_run: bool = False
    sync_content: bool = True
    include_patterns: list[str] | None = None
    exclude_patterns: list[str] | None = None
    generate_embeddings: bool = False


@dataclass
class SysAccessParams:
    """Parameters for sys_access(): Check if a file or directory exists."""

    path: str


@dataclass
class SysIsDirectoryParams:
    """Parameters for sys_is_directory(): Check if path is a directory (explicit or implicit)."""

    path: str


@dataclass
class SysMkdirParams:
    """Parameters for sys_mkdir(): Create a directory (parents=True for mkdir -p)."""

    path: str
    parents: bool = False
    exist_ok: bool = False


@dataclass
class SysReaddirParams:
    """Parameters for sys_readdir(): List directory entries (POSIX readdir(3))."""

    path: str = "/"
    recursive: bool = True
    details: bool = False
    show_parsed: bool = True
    context: Any = None
    limit: int | None = None
    cursor: str | None = None


@dataclass
class SysRenameParams:
    """Parameters for sys_rename(): Rename/move a file by updating its path in metadata."""

    old_path: str
    new_path: str


@dataclass
class SysRmdirParams:
    """Parameters for sys_rmdir(): Remove a directory (recursive=True for rm -rf)."""

    path: str
    recursive: bool = False
    subject: tuple[str, str] | None = None
    zone_id: str | None = None
    agent_id: str | None = None
    is_admin: bool | None = None

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.subject, list):
            object.__setattr__(self, "subject", tuple(self.subject))


@dataclass
class SysStatParams:
    """Parameters for sys_stat(): Get file metadata without reading content (FUSE getattr)."""

    path: str


@dataclass
class SysUnlinkParams:
    """Parameters for sys_unlink(): Delete a file or memory."""

    path: str


@dataclass
class SysWriteParams:
    """Parameters for sys_write(): Write content to a file with optional optimistic concurrency control."""

    path: str
    content: bytes | str
    if_match: str | None = None
    if_none_match: bool = False
    force: bool = False
    lock: bool = False
    lock_timeout: float = 30.0


@dataclass
class UnregisterMemoryParams:
    """Parameters for unregister_memory(): Unregister a memory (does NOT delete files)."""

    path: str


@dataclass
class UnregisterWorkspaceParams:
    """Parameters for unregister_workspace(): Unregister a workspace (does NOT delete files)."""

    path: str


@dataclass
class UpdateAgentParams:
    """Parameters for update_agent(): Update an existing agent's configuration (v0.5.1)."""

    agent_id: str
    name: str | None = None
    description: str | None = None
    metadata: dict | None = None
    context: dict | None = None


@dataclass
class UpdateWorkspaceParams:
    """Parameters for update_workspace(): Update an existing workspace configuration."""

    path: str
    name: str | None = None
    description: str | None = None
    metadata: dict | None = None


@dataclass
class WorkspaceDiffParams:
    """Parameters for workspace_diff(): Compare two workspace snapshots."""

    snapshot_1: int
    snapshot_2: int
    workspace_path: str | None = None


@dataclass
class WorkspaceLogParams:
    """Parameters for workspace_log(): List snapshot history for workspace."""

    workspace_path: str | None = None
    limit: int = 100


@dataclass
class WorkspaceRestoreParams:
    """Parameters for workspace_restore(): Restore workspace to a previous snapshot."""

    snapshot_number: int
    workspace_path: str | None = None


@dataclass
class WorkspaceSnapshotParams:
    """Parameters for workspace_snapshot(): Create a snapshot of a registered workspace."""

    workspace_path: str | None = None
    description: str | None = None
    tags: list[str] | None = None
    created_by: str | None = None
    context: dict | None = None


@dataclass
class WriteBatchParams:
    """Parameters for write_batch(): Write multiple files in a single transaction for improved performance."""

    files: list[tuple[str, bytes]]

    def __post_init__(self) -> None:
        """Convert lists to tuples (JSON deserializes tuples as lists)."""
        if isinstance(self.files, list):
            object.__setattr__(self, "files", tuple(self.files))


METHOD_PARAMS: dict[str, type] = {
    "access_share_link": AccessShareLinkParams,
    "ace_add_feedback": AceAddFeedbackParams,
    "ace_complete_trajectory": AceCompleteTrajectoryParams,
    "ace_create_playbook": AceCreatePlaybookParams,
    "ace_get_effective_score": AceGetEffectiveScoreParams,
    "ace_get_playbook": AceGetPlaybookParams,
    "ace_get_trajectory_feedback": AceGetTrajectoryFeedbackParams,
    "ace_log_trajectory_step": AceLogTrajectoryStepParams,
    "ace_mark_for_relearning": AceMarkForRelearningParams,
    "ace_query_playbooks": AceQueryPlaybooksParams,
    "ace_query_trajectories": AceQueryTrajectoriesParams,
    "ace_start_trajectory": AceStartTrajectoryParams,
    "add_mount": AddMountParams,
    "agent_heartbeat": AgentHeartbeatParams,
    "agent_list_by_zone": AgentListByZoneParams,
    "agent_transition": AgentTransitionParams,
    "append": AppendParams,
    "backfill_directory_index": BackfillDirectoryIndexParams,
    "cancel_sync_job": CancelSyncJobParams,
    "cancel_task": CancelTaskParams,
    "create_share_link": CreateShareLinkParams,
    "delete_agent": DeleteAgentParams,
    "delete_bulk": DeleteBulkParams,
    "delete_connector": DeleteConnectorParams,
    "delete_saved_mount": DeleteSavedMountParams,
    "deprovision_user": DeprovisionUserParams,
    "diff_versions": DiffVersionsParams,
    "edit": EditParams,
    "exists_batch": ExistsBatchParams,
    "get_agent": GetAgentParams,
    "get_etag": GetEtagParams,
    "get_memory_info": GetMemoryInfoParams,
    "get_mount": GetMountParams,
    "get_share_link": GetShareLinkParams,
    "get_share_link_access_logs": GetShareLinkAccessLogsParams,
    "get_sync_job": GetSyncJobParams,
    "get_task": GetTaskParams,
    "get_task_stats": GetTaskStatsParams,
    "get_top_level_mounts": GetTopLevelMountsParams,
    "get_version": GetVersionParams,
    "get_workspace_info": GetWorkspaceInfoParams,
    "glob": GlobParams,
    "glob_batch": GlobBatchParams,
    "grep": GrepParams,
    "has_mount": HasMountParams,
    "list": ListParams,
    "list_agents": ListAgentsParams,
    "list_connectors": ListConnectorsParams,
    "list_incoming_shares": ListIncomingSharesParams,
    "list_mounts": ListMountsParams,
    "list_outgoing_shares": ListOutgoingSharesParams,
    "list_queue_tasks": ListQueueTasksParams,
    "list_registered_memories": ListRegisteredMemoriesParams,
    "list_saved_mounts": ListSavedMountsParams,
    "list_share_links": ListShareLinksParams,
    "list_sync_jobs": ListSyncJobsParams,
    "list_versions": ListVersionsParams,
    "list_workspaces": ListWorkspacesParams,
    "load_mount": LoadMountParams,
    "make_private": MakePrivateParams,
    "make_public": MakePublicParams,
    "mcp_connect": MCPConnectParams,
    "mcp_list_mounts": MCPListMountsParams,
    "mcp_list_tools": MCPListToolsParams,
    "mcp_mount": MCPMountParams,
    "mcp_sync": MCPSyncParams,
    "mcp_unmount": MCPUnmountParams,
    "metadata_batch": MetadataBatchParams,
    "namespace_delete": NamespaceDeleteParams,
    "namespace_list": NamespaceListParams,
    "oauth_list_credentials": OAuthListCredentialsParams,
    "oauth_list_providers": OAuthListProvidersParams,
    "oauth_revoke_credential": OAuthRevokeCredentialParams,
    "oauth_test_credential": OAuthTestCredentialParams,
    "provision_user": ProvisionUserParams,
    "read_bulk": ReadBulkParams,
    "rebac_check": RebacCheckParams,
    "rebac_create": RebacCreateParams,
    "rebac_delete": RebacDeleteParams,
    "rebac_expand": RebacExpandParams,
    "rebac_explain": RebacExplainParams,
    "rebac_list_objects": RebacListObjectsParams,
    "rebac_list_tuples": RebacListTuplesParams,
    "register_agent": RegisterAgentParams,
    "register_memory": RegisterMemoryParams,
    "register_workspace": RegisterWorkspaceParams,
    "remove_mount": RemoveMountParams,
    "rename_bulk": RenameBulkParams,
    "revoke_share": RevokeShareParams,
    "revoke_share_by_id": RevokeShareByIdParams,
    "revoke_share_link": RevokeShareLinkParams,
    "rollback": RollbackParams,
    "save_mount": SaveMountParams,
    "semantic_search_index": SemanticSearchIndexParams,
    "share_with_user": ShareWithUserParams,
    "skills_discover": SkillsDiscoverParams,
    "skills_export": SkillsExportParams,
    "skills_get_prompt_context": SkillsGetPromptContextParams,
    "skills_import": SkillsImportParams,
    "skills_load": SkillsLoadParams,
    "skills_share": SkillsShareParams,
    "skills_subscribe": SkillsSubscribeParams,
    "skills_unshare": SkillsUnshareParams,
    "skills_unsubscribe": SkillsUnsubscribeParams,
    "skills_validate_zip": SkillsValidateZipParams,
    "snapshot_begin": SnapshotBeginParams,
    "snapshot_commit": SnapshotCommitParams,
    "snapshot_rollback": SnapshotRollbackParams,
    "stat": StatParams,
    "stat_bulk": StatBulkParams,
    "submit_task": SubmitTaskParams,
    "sync_mount": SyncMountParams,
    "sync_mount_async": SyncMountAsyncParams,
    "sys_access": SysAccessParams,
    "sys_is_directory": SysIsDirectoryParams,
    "sys_mkdir": SysMkdirParams,
    "sys_readdir": SysReaddirParams,
    "sys_rename": SysRenameParams,
    "sys_rmdir": SysRmdirParams,
    "sys_stat": SysStatParams,
    "sys_unlink": SysUnlinkParams,
    "sys_write": SysWriteParams,
    "unregister_memory": UnregisterMemoryParams,
    "unregister_workspace": UnregisterWorkspaceParams,
    "update_agent": UpdateAgentParams,
    "update_workspace": UpdateWorkspaceParams,
    "workspace_diff": WorkspaceDiffParams,
    "workspace_log": WorkspaceLogParams,
    "workspace_restore": WorkspaceRestoreParams,
    "workspace_snapshot": WorkspaceSnapshotParams,
    "write_batch": WriteBatchParams,
}
