# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus/grpc/vfs/vfs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nexus/grpc/vfs/vfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18nexus/grpc/vfs/vfs.proto\x12\x0enexus.grpc.vfs\"B\n\x0b\x43\x61llRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x12\n\nauth_token\x18\x03 \x01(\t\"1\n\x0c\x43\x61llResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x10\n\x08is_error\x18\x02 \x01(\x08\x32T\n\x0fNexusVFSService\x12\x41\n\x04\x43\x61ll\x12\x1b.nexus.grpc.vfs.CallRequest\x1a\x1c.nexus.grpc.vfs.CallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus.grpc.vfs.vfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLREQUEST']._serialized_start=44
  _globals['_CALLREQUEST']._serialized_end=110
  _globals['_CALLRESPONSE']._serialized_start=112
  _globals['_CALLRESPONSE']._serialized_end=161
  _globals['_NEXUSVFSSERVICE']._serialized_start=163
  _globals['_NEXUSVFSSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
