# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nexus.grpc.vfs import vfs_pb2 as nexus_dot_grpc_dot_vfs_dot_vfs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus/grpc/vfs/vfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusVFSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Call',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Read',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Write',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Delete',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Ping',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingResponse.FromString,
                _registered_method=True)
        self.BatchRead = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/BatchRead',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadResponse.FromString,
                _registered_method=True)
        self.BatchWrite = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/BatchWrite',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Stat',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Readdir = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Readdir',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirResponse.FromString,
                _registered_method=True)
        self.BatchStat = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/BatchStat',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatResponse.FromString,
                _registered_method=True)
        self.Setattr = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Setattr',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Rename',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameResponse.FromString,
                _registered_method=True)
        self.Copy = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Copy',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyResponse.FromString,
                _registered_method=True)
        self.Lock = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Lock',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockResponse.FromString,
                _registered_method=True)
        self.Unlock = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Unlock',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_unary(
                '/nexus.grpc.vfs.NexusVFSService/Watch',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchResponse.FromString,
                _registered_method=True)


class NexusVFSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Generic dispatch RPC — method name + JSON-encoded params.
        Server routes to the same dispatch_method() as the HTTP endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Typed RPCs for content operations — native bytes, no JSON/base64.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check with server metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRead(self, request, context):
        """Vectored batch read (Issue #4058). Per-request errors are reported
        per-item; outer Status is reserved for transport-level failures.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchWrite(self, request, context):
        """Vectored batch write — native bytes (no base64 tax) + per-item
        error isolation. Replaces the generic `write_batch` Call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Typed metadata stat — the hottest metadata op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readdir(self, request, context):
        """Typed directory listing — metastore + backend merge, procfs intercepts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchStat(self, request, context):
        """Vectored stat — single redb txn on the optimized KernelConvenience
        override. Per-path not-found is in-band (`found = false`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Setattr(self, request, context):
        """Typed attribute set / inode create. Exposes the subset of the
        21-param inherent sys_setattr that crosses the JSON wire today —
        Arc<ObjectStore>, metastore, raft_backend, read_fd/write_fd, source,
        and remote_metastore stay off this RPC (they need in-process refs).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Typed rename / server-side copy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Copy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lock(self, request, context):
        """Typed advisory-lock acquire / release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Typed file-event watch (blocking, inotify-shaped).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusVFSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingResponse.SerializeToString,
            ),
            'BatchRead': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRead,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadResponse.SerializeToString,
            ),
            'BatchWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchWrite,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatResponse.SerializeToString,
            ),
            'Readdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Readdir,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirResponse.SerializeToString,
            ),
            'BatchStat': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchStat,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatResponse.SerializeToString,
            ),
            'Setattr': grpc.unary_unary_rpc_method_handler(
                    servicer.Setattr,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameResponse.SerializeToString,
            ),
            'Copy': grpc.unary_unary_rpc_method_handler(
                    servicer.Copy,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyResponse.SerializeToString,
            ),
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockResponse.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockResponse.SerializeToString,
            ),
            'Watch': grpc.unary_unary_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.grpc.vfs.NexusVFSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.grpc.vfs.NexusVFSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusVFSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Call',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Read',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Write',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Delete',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Ping',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/BatchRead',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/BatchWrite',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Stat',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Readdir',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.ReaddirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/BatchStat',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.BatchStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Setattr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Setattr',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.SetattrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Rename',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.RenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Copy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Copy',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.CopyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Lock',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.LockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Unlock',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.UnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.NexusVFSService/Watch',
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_vfs__pb2.WatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
