# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nexus.grpc.vfs import zone_runtime_pb2 as nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus/grpc/vfs/zone_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZoneRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ZoneCreate = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneCreate',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneCreateRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.ZoneJoin = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneJoin',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneJoinRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.ZoneStatus = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneStatus',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusResponse.FromString,
                _registered_method=True)
        self.ZoneMount = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneMount',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneMountRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.ZoneUnmount = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneUnmount',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneUnmountRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.ZoneRemoveReplica = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneRemoveReplica',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneRemoveReplicaRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.ZoneDeprovision = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/ZoneDeprovision',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneDeprovisionRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
                _registered_method=True)
        self.GetZoneOperation = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/GetZoneOperation',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetZoneOperationRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneOperationRecord.FromString,
                _registered_method=True)
        self.GetRuntimeCapabilities = channel.unary_unary(
                '/nexus.grpc.vfs.ZoneRuntimeService/GetRuntimeCapabilities',
                request_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesRequest.SerializeToString,
                response_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesResponse.FromString,
                _registered_method=True)


class ZoneRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ZoneCreate(self, request, context):
        """Create a new tenant/data zone. Idempotent per operation_id; the same
        address book replays the original receipt, a different one is refused.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneJoin(self, request, context):
        """Join an existing zone. NEVER bootstraps a founder — a join that cannot
        reach a peer fails loudly instead of degrading into a create (R9).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneStatus(self, request, context):
        """Hosted/resident/local-not-found presence + raft facts (R10).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneMount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneUnmount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneRemoveReplica(self, request, context):
        """Destroy this node's local replica only — no global Deleted state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZoneDeprovision(self, request, context):
        """Full lifecycle teardown: deletion epoch/tombstone + peer fan-out, so an
        old replica that missed the fan-out cannot resurrect the zone (R12).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZoneOperation(self, request, context):
        """Journal lookup for a mutation whose response was lost: PENDING (still
        executing / crashed mid-flight), or COMPLETED + the original receipt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeCapabilities(self, request, context):
        """Boot/readiness capability snapshot for Nexus production assembly (R13).
        Unavailable until the data plane is wired — the readiness semantics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZoneRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ZoneCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneCreate,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneCreateRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'ZoneJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneJoin,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneJoinRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'ZoneStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneStatus,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusResponse.SerializeToString,
            ),
            'ZoneMount': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneMount,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneMountRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'ZoneUnmount': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneUnmount,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneUnmountRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'ZoneRemoveReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneRemoveReplica,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneRemoveReplicaRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'ZoneDeprovision': grpc.unary_unary_rpc_method_handler(
                    servicer.ZoneDeprovision,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneDeprovisionRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.SerializeToString,
            ),
            'GetZoneOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZoneOperation,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetZoneOperationRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneOperationRecord.SerializeToString,
            ),
            'GetRuntimeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeCapabilities,
                    request_deserializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesRequest.FromString,
                    response_serializer=nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.grpc.vfs.ZoneRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.grpc.vfs.ZoneRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZoneRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ZoneCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneCreate',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneCreateRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneJoin',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneJoinRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneStatus',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneMount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneMount',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneMountRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneUnmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneUnmount',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneUnmountRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneRemoveReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneRemoveReplica',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneRemoveReplicaRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZoneDeprovision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/ZoneDeprovision',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneDeprovisionRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetZoneOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/GetZoneOperation',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetZoneOperationRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.ZoneOperationRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.grpc.vfs.ZoneRuntimeService/GetRuntimeCapabilities',
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesRequest.SerializeToString,
            nexus_dot_grpc_dot_vfs_dot_zone__runtime__pb2.GetRuntimeCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
