name: rename-tracker
description: Track file renames and maintain history
version: 1.0

triggers:
  - type: file_rename
    pattern: /documents/**/*

actions:
  - name: log_rename
    type: python
    code: |
      old_path = variables.get('old_path', 'unknown')
      new_path = variables.get('new_path', 'unknown')
      print(f"RENAMED: {old_path} → {new_path}")
      result = {"old": old_path, "new": new_path}

  - name: update_metadata
    type: metadata
    file_path: "{new_path}"
    metadata:
      previous_name: "{old_path}"
      renamed_at: "{timestamp}"
      rename_count: "1"
