name: generate-report
description: Manually triggered report generation
version: 1.0

triggers:
  - type: manual

actions:
  - name: collect_data
    type: python
    code: |
      from nexus import connect
      nx = connect()
      # Collect data from various sources
      print("Collecting report data...")
      result = {"data_points": 1234, "sources": 5}

  - name: generate_report
    type: python
    code: |
      data_points = collect_data_output.get('data_points', 0)
      print(f"Generating report with {data_points} data points...")
      report_content = f"# Monthly Report\n\nData Points: {data_points}\n"
      result = {"content": report_content}

  - name: save_report
    type: python
    code: |
      from nexus import connect
      from datetime import datetime
      nx = connect()
      report_path = f"/reports/monthly-{datetime.now().strftime('%Y-%m')}.md"
      content = generate_report_output.get('content', '')
      # nx.write(report_path, content.encode())
      print(f"Report saved to: {report_path}")
      result = {"path": report_path}

  - name: send_notification
    type: webhook
    url: https://notifications.example.com/api/report-ready
    method: POST
    body:
      report_path: "{save_report_output.path}"
      timestamp: "{timestamp}"
