// AUTO-GENERATED by scripts/codegen_kernel_abi.py — DO NOT EDIT
//! PyO3 transport wrapper — bridges Python <-> pure Rust kernel.
//!
//! This single file contains ALL PyO3 code for the kernel boundary:
//!   - Direction 1 (WRAPPER): PyKernel wraps pure Rust Kernel
//!   - Direction 2 (DISPATCH): Python hooks/resolvers/observers -> Rust traits
//!   - Direction 3 (PILLAR): Python storage backends -> Rust trait implementations
//!   - Error conversion: KernelError -> PyErr
//!   - FileMetadata conversion helpers
//!
//! Re-generate: python scripts/codegen_kernel_abi.py

#![allow(dead_code)]

use parking_lot::Mutex;
use pyo3::prelude::*;
use pyo3::types::{PyBytes, PyDict, PyList};
use std::io;
use std::path::Path;
use std::sync::Arc;

use crate::backend::{
    CasLocalBackend, LocalConnectorBackend, ObjectStore, PathLocalBackend, StorageError,
    WriteResult,
};
use crate::dispatch::{MutationObserver, PathResolver};
use crate::hook_registry::{HookRegistry, InterceptHook, ObserverPair, ObserverRegistry};
use crate::kernel::{Kernel, KernelError, OperationContext};
use crate::lock::VFSLockManager;
use crate::metastore::{FileMetadata, Metastore, MetastoreError};
use crate::router::{RouteError, RustRouteResult};

// ═══════════════════════════════════════════════════════════════════════════
// Error conversion: KernelError -> PyErr (cached exception classes)
// ═══════════════════════════════════════════════════════════════════════════

/// Cached exception class references — initialized once on first use.
struct ExceptionCache {
    invalid_path: Py<PyAny>,
    file_not_found: Py<PyAny>,
}

static EXCEPTION_CACHE: std::sync::OnceLock<Option<ExceptionCache>> = std::sync::OnceLock::new();

fn get_exception_cache(py: Python<'_>) -> Option<&'static ExceptionCache> {
    EXCEPTION_CACHE
        .get_or_init(|| {
            let m = py.import("nexus.contracts.exceptions").ok()?;
            let invalid_path = m.getattr("InvalidPathError").ok()?.unbind();
            let file_not_found = m.getattr("NexusFileNotFoundError").ok()?.unbind();
            Some(ExceptionCache {
                invalid_path,
                file_not_found,
            })
        })
        .as_ref()
}

impl From<KernelError> for PyErr {
    fn from(e: KernelError) -> PyErr {
        match e {
            KernelError::InvalidPath(msg) => Python::attach(|py| {
                if let Some(cache) = get_exception_cache(py) {
                    cache
                        .invalid_path
                        .bind(py)
                        .call1((&msg,))
                        .map(PyErr::from_value)
                        .unwrap_or_else(|_| pyo3::exceptions::PyValueError::new_err(msg))
                } else {
                    pyo3::exceptions::PyValueError::new_err(msg)
                }
            }),
            KernelError::FileNotFound(path) => Python::attach(|py| {
                if let Some(cache) = get_exception_cache(py) {
                    cache
                        .file_not_found
                        .bind(py)
                        .call1((&path,))
                        .map(PyErr::from_value)
                        .unwrap_or_else(|_| pyo3::exceptions::PyFileNotFoundError::new_err(path))
                } else {
                    pyo3::exceptions::PyFileNotFoundError::new_err(path)
                }
            }),
            KernelError::Route(RouteError::NotMounted(msg)) => {
                pyo3::exceptions::PyValueError::new_err(msg)
            }
            KernelError::Route(RouteError::AccessDenied(msg)) => {
                pyo3::exceptions::PyPermissionError::new_err(msg)
            }
            KernelError::IOError(msg) => pyo3::exceptions::PyIOError::new_err(msg),
            KernelError::TrieError(msg) => pyo3::exceptions::PyValueError::new_err(msg),
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// FileMetadata conversion helpers (from generated_store.rs)
// ═══════════════════════════════════════════════════════════════════════════

/// Extract Rust FileMetadata from a Python FileMetadata object.
fn extract_metadata(
    py: Python<'_>,
    obj: &Bound<'_, PyAny>,
) -> Result<FileMetadata, MetastoreError> {
    let get_str = |name: &str| -> Result<String, MetastoreError> {
        obj.getattr(name)
            .and_then(|v| v.extract::<String>())
            .map_err(|e| MetastoreError::IOError(format!("field {name}: {e}")))
    };
    let get_opt_str = |name: &str| -> Result<Option<String>, MetastoreError> {
        match obj.getattr(name) {
            Ok(v) if v.is_none() => Ok(None),
            Ok(v) => v
                .extract::<String>()
                .map(Some)
                .map_err(|e| MetastoreError::IOError(format!("field {name}: {e}"))),
            Err(e) => Err(MetastoreError::IOError(format!("field {name}: {e}"))),
        }
    };

    let _ = py;
    Ok(FileMetadata {
        path: get_str("path")?,
        backend_name: get_str("backend_name")?,
        physical_path: get_str("physical_path")?,
        size: obj
            .getattr("size")
            .and_then(|v| v.extract::<u64>())
            .map_err(|e| MetastoreError::IOError(format!("field size: {e}")))?,
        etag: get_opt_str("etag")?,
        version: obj
            .getattr("version")
            .and_then(|v| v.extract::<u32>())
            .map_err(|e| MetastoreError::IOError(format!("field version: {e}")))?,
        entry_type: obj
            .getattr("entry_type")
            .and_then(|v| v.extract::<u8>())
            .map_err(|e| MetastoreError::IOError(format!("field entry_type: {e}")))?,
        zone_id: get_opt_str("zone_id")?,
        mime_type: get_opt_str("mime_type")?,
    })
}

/// Convert Rust FileMetadata -> Python FileMetadata (for metastore.put()).
fn to_python_metadata<'py>(
    py: Python<'py>,
    meta: &FileMetadata,
) -> Result<Bound<'py, PyAny>, MetastoreError> {
    fn err(e: PyErr) -> MetastoreError {
        MetastoreError::IOError(format!("to_python_metadata: {e}"))
    }
    let cls = py
        .import("nexus.contracts.metadata")
        .map_err(err)?
        .getattr("FileMetadata")
        .map_err(err)?;
    let kwargs = PyDict::new(py);
    kwargs.set_item("path", &meta.path).map_err(err)?;
    kwargs
        .set_item("backend_name", &meta.backend_name)
        .map_err(err)?;
    kwargs
        .set_item("physical_path", &meta.physical_path)
        .map_err(err)?;
    kwargs.set_item("size", meta.size).map_err(err)?;
    kwargs.set_item("etag", meta.etag.as_deref()).map_err(err)?;
    kwargs.set_item("version", meta.version).map_err(err)?;
    kwargs
        .set_item("entry_type", meta.entry_type)
        .map_err(err)?;
    kwargs
        .set_item("zone_id", meta.zone_id.as_deref())
        .map_err(err)?;
    kwargs
        .set_item("mime_type", meta.mime_type.as_deref())
        .map_err(err)?;
    cls.call((), Some(&kwargs)).map_err(err)
}

/// Convert Rust OperationContext -> Python OperationContext.
///
/// Forwards ALL fields so Python hooks see the full credential.
fn rust_ctx_to_python<'py>(
    py: Python<'py>,
    ctx: &OperationContext,
    backend_path: &str,
) -> Result<Bound<'py, PyAny>, String> {
    let cls = py
        .import("nexus.contracts.types")
        .and_then(|m| m.getattr("OperationContext"))
        .map_err(|e| format!("import OperationContext: {e}"))?;
    let kwargs = PyDict::new(py);
    let _ = kwargs.set_item("user_id", &ctx.user_id);
    // Use context_zone_id (caller's zone, may be None) for Python context,
    // NOT routing zone_id (always set to NexusFS instance zone).
    match &ctx.context_zone_id {
        Some(z) => {
            let _ = kwargs.set_item("zone_id", z);
        }
        None => {
            let _ = kwargs.set_item("zone_id", py.None());
        }
    }
    let _ = kwargs.set_item("is_admin", ctx.is_admin);
    let _ = kwargs.set_item("is_system", ctx.is_system);
    let _ = kwargs.set_item("backend_path", backend_path);
    let groups = PyList::new(py, &ctx.groups).map_err(|e| format!("groups: {e}"))?;
    let _ = kwargs.set_item("groups", groups);
    if let Some(ref agent_id) = ctx.agent_id {
        let _ = kwargs.set_item("agent_id", agent_id);
    }
    // admin_capabilities: Vec<String> → Python set[str]
    let cap_set = pyo3::types::PySet::empty(py).map_err(|e| format!("set(): {e}"))?;
    for cap in &ctx.admin_capabilities {
        let _ = cap_set.add(cap);
    }
    let _ = kwargs.set_item("admin_capabilities", &cap_set);
    let _ = kwargs.set_item("subject_type", &ctx.subject_type);
    if let Some(ref sid) = ctx.subject_id {
        let _ = kwargs.set_item("subject_id", sid);
    }
    if !ctx.request_id.is_empty() {
        let _ = kwargs.set_item("request_id", &ctx.request_id);
    }
    cls.call((), Some(&kwargs))
        .map_err(|e| format!("OperationContext(): {e}"))
}

// ═══════════════════════════════════════════════════════════════════════════
// Direction 3 (PILLAR): Store adapters — Python ABC -> Rust trait
// ═══════════════════════════════════════════════════════════════════════════

// ── PyObjectStoreAdapter ────────────────────────────────────────

/// Wraps Python `ObjectStoreABC` -> Rust `ObjectStore` trait.
///
/// Transitional adapter: Python backend via GIL (cold path).
pub(crate) struct PyObjectStoreAdapter {
    inner: Py<PyAny>,
    backend_name: String,
}

unsafe impl Send for PyObjectStoreAdapter {}
unsafe impl Sync for PyObjectStoreAdapter {}

impl PyObjectStoreAdapter {
    pub(crate) fn new(py: Python<'_>, inner: Py<PyAny>) -> Self {
        let name = inner
            .bind(py)
            .getattr("name")
            .and_then(|n| n.extract::<String>())
            .unwrap_or_else(|_| "<backend>".to_string());
        Self {
            inner,
            backend_name: name,
        }
    }
}

impl ObjectStore for PyObjectStoreAdapter {
    fn name(&self) -> &str {
        &self.backend_name
    }

    fn write_content(
        &self,
        content: &[u8],
        content_id: &str,
        ctx: &crate::kernel::OperationContext,
    ) -> Result<WriteResult, StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            // Convert Rust ctx → Python OperationContext (carries backend_path for PAS)
            let py_ctx = rust_ctx_to_python(py, ctx, content_id)
                .map_err(|e| StorageError::IOError(io::Error::other(e)))?;
            let kwargs = pyo3::types::PyDict::new(py);
            let _ = kwargs.set_item("context", &py_ctx);
            let result = obj
                .call_method("write_content", (content, content_id), Some(&kwargs))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            // Python ObjectStoreABC.write_content() returns WriteResult
            let cid = result
                .getattr("content_id")
                .and_then(|v| v.extract::<String>())
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            let version = result
                .getattr("version")
                .and_then(|v| v.extract::<String>())
                .unwrap_or_else(|_| cid.clone());
            let size = result
                .getattr("size")
                .and_then(|v| v.extract::<u64>())
                .unwrap_or(content.len() as u64);
            Ok(WriteResult {
                content_id: cid,
                version,
                size,
            })
        })
    }

    fn read_content(
        &self,
        content_id: &str,
        backend_path: &str,
        ctx: &crate::kernel::OperationContext,
    ) -> Result<Vec<u8>, StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            // Convert Rust OperationContext → Python OperationContext
            let py_ctx = rust_ctx_to_python(py, ctx, backend_path)
                .map_err(|e| StorageError::IOError(io::Error::other(e)))?;
            let result = obj
                .call_method(
                    "read_content",
                    (content_id,),
                    Some(&{
                        let kw = pyo3::types::PyDict::new(py);
                        let _ = kw.set_item("context", &py_ctx);
                        kw
                    }),
                )
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            result
                .extract::<Vec<u8>>()
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))
        })
    }

    fn delete_content(&self, content_id: &str) -> Result<(), StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            obj.call_method1("delete_content", (content_id,))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            Ok(())
        })
    }

    fn get_content_size(&self, content_id: &str) -> Result<u64, StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj
                .call_method1("get_content_size", (content_id,))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            result
                .extract::<u64>()
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))
        })
    }

    fn mkdir(&self, path: &str, parents: bool, exist_ok: bool) -> Result<(), StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            obj.call_method1("mkdir", (path, parents, exist_ok))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            Ok(())
        })
    }

    fn rmdir(&self, path: &str, recursive: bool) -> Result<(), StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            obj.call_method1("rmdir", (path, recursive))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            Ok(())
        })
    }

    fn delete_file(&self, path: &str) -> Result<(), StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            obj.call_method1("delete_file", (path,))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            Ok(())
        })
    }

    fn rename(&self, old_path: &str, new_path: &str) -> Result<(), StorageError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            obj.call_method1("rename", (old_path, new_path))
                .map_err(|e| StorageError::IOError(io::Error::other(e.to_string())))?;
            Ok(())
        })
    }
}

// ── PyMetastoreAdapter ──────────────────────────────────────────

/// Wraps Python `MetastoreABC` -> Rust `Metastore` trait.
///
/// Transitional adapter: Python backend via GIL (cold path).
pub(crate) struct PyMetastoreAdapter {
    inner: Py<PyAny>,
}

unsafe impl Send for PyMetastoreAdapter {}
unsafe impl Sync for PyMetastoreAdapter {}

impl PyMetastoreAdapter {
    pub(crate) fn new(inner: Py<PyAny>) -> Self {
        Self { inner }
    }
}

impl Metastore for PyMetastoreAdapter {
    fn get(&self, path: &str) -> Result<Option<FileMetadata>, MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj
                .call_method1("get", (path,))
                .map_err(|e| MetastoreError::IOError(format!("metastore.get({path}): {e}")))?;
            if result.is_none() {
                return Ok(None);
            }
            extract_metadata(py, &result).map(Some)
        })
    }

    fn put(&self, path: &str, metadata: FileMetadata) -> Result<(), MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let py_meta = to_python_metadata(py, &metadata)?;
            obj.call_method1("put", (path, py_meta))
                .map_err(|e| MetastoreError::IOError(format!("metastore.put({path}): {e}")))?;
            Ok(())
        })
    }

    fn delete(&self, path: &str) -> Result<bool, MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj
                .call_method1("delete", (path,))
                .map_err(|e| MetastoreError::IOError(format!("metastore.delete({path}): {e}")))?;
            result
                .extract::<bool>()
                .map_err(|e| MetastoreError::IOError(format!("metastore.delete({path}): {e}")))
        })
    }

    fn list(&self, prefix: &str) -> Result<Vec<FileMetadata>, MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj
                .call_method1("list", (prefix,))
                .map_err(|e| MetastoreError::IOError(format!("metastore.list({prefix}): {e}")))?;
            let iter = result
                .try_iter()
                .map_err(|e| MetastoreError::IOError(format!("metastore.list iter: {e}")))?;
            let mut items = Vec::new();
            for item in iter {
                let item =
                    item.map_err(|e| MetastoreError::IOError(format!("metastore.list item: {e}")))?;
                items.push(extract_metadata(py, &item)?);
            }
            Ok(items)
        })
    }

    fn exists(&self, path: &str) -> Result<bool, MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj
                .call_method1("exists", (path,))
                .map_err(|e| MetastoreError::IOError(format!("metastore.exists({path}): {e}")))?;
            result
                .extract::<bool>()
                .map_err(|e| MetastoreError::IOError(format!("metastore.exists({path}): {e}")))
        })
    }

    fn delete_batch(&self, paths: &[String]) -> Result<usize, MetastoreError> {
        Python::attach(|py| {
            let obj = self.inner.bind(py);
            let result = obj.call_method1("delete_batch", (paths,)).map_err(|e| {
                MetastoreError::IOError(format!("metastore.delete_batch({paths:?}): {e}"))
            })?;
            result.extract::<usize>().map_err(|e| {
                MetastoreError::IOError(format!("metastore.delete_batch({paths:?}): {e}"))
            })
        })
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Direction 2 (DISPATCH): Python hooks/resolvers/observers -> Rust traits
// ═══════════════════════════════════════════════════════════════════════════

// ── PyInterceptHookAdapter ──────────────────────────────────────

/// Wraps Python -> Rust `InterceptHook` trait.
pub(crate) struct PyInterceptHookAdapter {
    inner: Py<PyAny>,
    hook_name: String,
}

unsafe impl Send for PyInterceptHookAdapter {}
unsafe impl Sync for PyInterceptHookAdapter {}

impl PyInterceptHookAdapter {
    pub(crate) fn new(py: Python<'_>, hook: Py<PyAny>) -> Self {
        let name = hook
            .bind(py)
            .getattr("name")
            .and_then(|n| n.extract::<String>())
            .unwrap_or_else(|_| "<hook>".to_string());
        Self {
            inner: hook,
            hook_name: name,
        }
    }
}

impl InterceptHook for PyInterceptHookAdapter {
    fn name(&self) -> &str {
        &self.hook_name
    }

    fn on_pre_read(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_read") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_read(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_read") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_write(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_write") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_write(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_write") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_delete(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_delete") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_delete(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_delete") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_rename(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_rename") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_rename(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_rename") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_mkdir(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_mkdir") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_mkdir(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_mkdir") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_rmdir(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_rmdir") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_rmdir(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_rmdir") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_copy(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_copy") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_copy(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_copy") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_stat(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_stat") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_stat(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_stat") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_access(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_access") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_access(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_access") {
                let _ = method.call1((ctx,));
            }
        });
    }

    fn on_pre_write_batch(&self, ctx: &Py<PyAny>) -> Result<(), PyErr> {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_pre_write_batch") {
                method.call1((ctx,))?;
            }
            Ok(())
        })
    }

    fn on_post_write_batch(&self, ctx: &Py<PyAny>) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_post_write_batch") {
                let _ = method.call1((ctx,));
            }
        });
    }
}

// ── PyPathResolverAdapter ───────────────────────────────────────

/// Wraps Python -> Rust `PathResolver` trait.
pub(crate) struct PyPathResolverAdapter {
    inner: Py<PyAny>,
}

unsafe impl Send for PyPathResolverAdapter {}
unsafe impl Sync for PyPathResolverAdapter {}

impl PathResolver for PyPathResolverAdapter {
    fn try_read(&self, path: &str) -> Option<Vec<u8>> {
        Python::attach(|py| {
            let result = self.inner.call_method1(py, "try_read", (path,)).ok()?;
            if result.is_none(py) {
                return None;
            }
            result.extract::<Vec<u8>>(py).ok()
        })
    }

    fn try_write(&self, path: &str, content: &[u8]) -> Option<()> {
        Python::attach(|py| {
            self.inner
                .call_method1(py, "try_write", (path, content))
                .ok()?;
            Some(())
        })
    }

    fn try_delete(&self, path: &str) -> Option<()> {
        Python::attach(|py| {
            self.inner.call_method1(py, "try_delete", (path,)).ok()?;
            Some(())
        })
    }
}

// ── PyMutationObserverAdapter ───────────────────────────────────

/// Wraps Python -> Rust `MutationObserver` trait.
pub(crate) struct PyMutationObserverAdapter {
    inner: Py<PyAny>,
}

unsafe impl Send for PyMutationObserverAdapter {}
unsafe impl Sync for PyMutationObserverAdapter {}

impl MutationObserver for PyMutationObserverAdapter {
    fn on_mutation(&self, event_type: u32, path: &str) {
        Python::attach(|py| {
            let hook = self.inner.bind(py);
            if let Ok(method) = hook.getattr("on_mutation") {
                let _ = method.call1((event_type, path));
            }
        });
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Direction 1 (WRAPPER): PyO3 wrapper types
// ═══════════════════════════════════════════════════════════════════════════

// ── PyOperationContext ──────────────────────────────────────────

/// Python-facing OperationContext (wraps pure Rust OperationContext).
#[pyclass(name = "OperationContext", get_all)]
#[derive(Clone, Debug)]
pub struct PyOperationContext {
    pub user_id: String,
    pub zone_id: String,
    pub is_admin: bool,
    pub agent_id: Option<String>,
    pub is_system: bool,
    pub groups: Vec<String>,
    pub admin_capabilities: Vec<String>,
    pub subject_type: String,
    pub subject_id: Option<String>,
    pub request_id: String,
    pub context_zone_id: Option<String>,
}

#[pymethods]
impl PyOperationContext {
    #[new]
    #[pyo3(signature = (user_id="anonymous", zone_id="root", is_admin=false, agent_id=None, is_system=false, groups=Vec::new(), admin_capabilities=Vec::new(), subject_type="user", subject_id=None, request_id="", context_zone_id=None))]
    #[allow(clippy::too_many_arguments)]
    fn new(
        user_id: &str,
        zone_id: &str,
        is_admin: bool,
        agent_id: Option<&str>,
        is_system: bool,
        groups: Vec<String>,
        admin_capabilities: Vec<String>,
        subject_type: &str,
        subject_id: Option<&str>,
        request_id: &str,
        context_zone_id: Option<&str>,
    ) -> Self {
        Self {
            user_id: user_id.to_string(),
            zone_id: zone_id.to_string(),
            is_admin,
            agent_id: agent_id.map(|s| s.to_string()),
            is_system,
            groups,
            admin_capabilities,
            subject_type: subject_type.to_string(),
            subject_id: subject_id.map(|s| s.to_string()),
            request_id: request_id.to_string(),
            context_zone_id: context_zone_id.map(|s| s.to_string()),
        }
    }
}

impl PyOperationContext {
    /// Convert to pure Rust OperationContext for kernel calls.
    fn to_rust(&self) -> OperationContext {
        OperationContext {
            user_id: self.user_id.clone(),
            zone_id: self.zone_id.clone(),
            is_admin: self.is_admin,
            agent_id: self.agent_id.clone(),
            is_system: self.is_system,
            groups: self.groups.clone(),
            admin_capabilities: self.admin_capabilities.clone(),
            subject_type: self.subject_type.clone(),
            subject_id: self.subject_id.clone(),
            request_id: self.request_id.clone(),
            context_zone_id: self.context_zone_id.clone(),
        }
    }
}

// ── PySysReadResult ─────────────────────────────────────────────

/// Python-facing SysReadResult (data is PyBytes, not Vec<u8>).
#[pyclass(name = "SysReadResult", get_all)]
pub struct PySysReadResult {
    pub hit: bool,
    pub data: Option<Py<PyBytes>>,
    pub post_hook_needed: bool,
    pub content_hash: Option<String>,
    pub entry_type: u8,
}

// ── PySysWriteResult ────────────────────────────────────────────

/// Python-facing SysWriteResult.
#[pyclass(name = "SysWriteResult", get_all)]
pub struct PySysWriteResult {
    pub hit: bool,
    pub content_id: Option<String>,
    pub post_hook_needed: bool,
    pub version: u32,
    pub size: u64,
}

// ── PySysUnlinkResult ───────────────────────────────────────────

/// Python-facing SysUnlinkResult.
#[pyclass(name = "SysUnlinkResult", get_all)]
pub struct PySysUnlinkResult {
    pub hit: bool,
    pub entry_type: u8,
    pub post_hook_needed: bool,
    pub path: String,
    pub etag: Option<String>,
    pub size: u64,
}

// ── PySysRenameResult ───────────────────────────────────────────

/// Python-facing SysRenameResult.
#[pyclass(name = "SysRenameResult", get_all)]
pub struct PySysRenameResult {
    pub hit: bool,
    pub success: bool,
    pub post_hook_needed: bool,
    pub is_directory: bool,
}

// ── PySysMkdirResult ────────────────────────────────────────────

/// Python-facing SysMkdirResult.
#[pyclass(name = "SysMkdirResult", get_all)]
pub struct PySysMkdirResult {
    pub hit: bool,
    pub post_hook_needed: bool,
}

// ── PySysRmdirResult ────────────────────────────────────────────

/// Python-facing SysRmdirResult.
#[pyclass(name = "SysRmdirResult", get_all)]
pub struct PySysRmdirResult {
    pub hit: bool,
    pub post_hook_needed: bool,
    pub children_deleted: usize,
}

// ── PyRustRouteResult ───────────────────────────────────────────

/// Python-facing RustRouteResult.
#[pyclass(name = "RustRouteResult")]
pub struct PyRustRouteResult {
    #[pyo3(get)]
    pub mount_point: String,
    #[pyo3(get)]
    pub backend_path: String,
    #[pyo3(get)]
    pub readonly: bool,
    #[pyo3(get)]
    pub io_profile: String,
}

impl From<RustRouteResult> for PyRustRouteResult {
    fn from(r: RustRouteResult) -> Self {
        Self {
            mount_point: r.mount_point,
            backend_path: r.backend_path,
            readonly: r.readonly,
            io_profile: r.io_profile,
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// PyKernel — wraps pure Rust Kernel + owns Hook/Observer registries
// ═══════════════════════════════════════════════════════════════════════════

/// Python-facing Kernel. Wraps the pure Rust `Kernel` and adds:
///   - Hook/Observer registries (PyO3-specific, stored here not in Rust Kernel)
///   - PRE-INTERCEPT dispatch (requires GIL for Python hook contexts)
///   - Type conversion (Vec<u8> -> PyBytes, StatResult -> PyDict, etc.)
#[pyclass(name = "Kernel")]
pub struct PyKernel {
    inner: Kernel,
    hooks: Mutex<HookRegistry>,
    observers: Mutex<ObserverRegistry>,
}

#[pymethods]
impl PyKernel {
    // ── Constructor ────────────────────────────────────────────────────

    #[new]
    fn new() -> Self {
        Self {
            inner: Kernel::new(),
            hooks: Mutex::new(HookRegistry::new()),
            observers: Mutex::new(ObserverRegistry::new()),
        }
    }

    // ── VFS Lock wiring ────────────────────────────────────────────────

    fn set_vfs_lock(&mut self, vfs_lock: &VFSLockManager) {
        self.inner.set_vfs_lock(Arc::clone(&vfs_lock.inner));
    }

    fn set_vfs_lock_timeout(&mut self, timeout_ms: u64) {
        self.inner.set_vfs_lock_timeout(timeout_ms);
    }

    // ── Metastore wiring ──────────────────────────────────────────────

    fn set_metastore(&mut self, metastore: Py<PyAny>) {
        self.inner
            .set_metastore(Box::new(PyMetastoreAdapter::new(metastore)));
    }

    /// Wire RedbMetastore by path — Rust kernel opens redb directly.
    /// Eliminates GIL crossing on every metastore.get/put.
    fn set_metastore_path(&mut self, path: &str) -> PyResult<()> {
        self.inner.set_metastore_path(path).map_err(Into::into)
    }

    // ── Metastore proxy methods (for RustMetastoreProxy) ──────────────

    fn metastore_get(&self, py: Python<'_>, path: &str) -> PyResult<Option<Py<PyAny>>> {
        match self
            .inner
            .metastore_get(path)
            .map_err::<PyErr, _>(Into::into)?
        {
            Some(meta) => {
                let obj = to_python_metadata(py, &meta)
                    .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{e:?}")))?;
                Ok(Some(obj.into()))
            }
            None => Ok(None),
        }
    }

    fn metastore_put(&self, py: Python<'_>, metadata: &Bound<'_, PyAny>) -> PyResult<()> {
        let meta = extract_metadata(py, metadata)
            .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{e:?}")))?;
        self.inner
            .metastore_put(&meta.path.clone(), meta)
            .map_err(Into::into)
    }

    fn metastore_delete(&self, path: &str) -> PyResult<bool> {
        self.inner.metastore_delete(path).map_err(Into::into)
    }

    fn metastore_list(&self, py: Python<'_>, prefix: &str) -> PyResult<Vec<Py<PyAny>>> {
        let items = self
            .inner
            .metastore_list(prefix)
            .map_err::<PyErr, _>(Into::into)?;
        let mut result = Vec::with_capacity(items.len());
        for meta in &items {
            result.push(
                to_python_metadata(py, meta)
                    .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{e:?}")))?
                    .into(),
            );
        }
        Ok(result)
    }

    fn metastore_exists(&self, path: &str) -> PyResult<bool> {
        self.inner.metastore_exists(path).map_err(Into::into)
    }

    fn metastore_get_batch(
        &self,
        py: Python<'_>,
        paths: Vec<String>,
    ) -> PyResult<Vec<Option<Py<PyAny>>>> {
        let items = self
            .inner
            .metastore_get_batch(&paths)
            .map_err::<PyErr, _>(Into::into)?;
        let mut result = Vec::with_capacity(items.len());
        for opt in &items {
            match opt {
                Some(meta) => result.push(Some(
                    to_python_metadata(py, meta)
                        .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{e:?}")))?
                        .into(),
                )),
                None => result.push(None),
            }
        }
        Ok(result)
    }

    fn metastore_put_batch(&self, py: Python<'_>, items: &Bound<'_, PyList>) -> PyResult<()> {
        let mut batch = Vec::with_capacity(items.len());
        for item in items.iter() {
            let meta = extract_metadata(py, &item)
                .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{e:?}")))?;
            let path = meta.path.clone();
            batch.push((path, meta));
        }
        self.inner.metastore_put_batch(&batch).map_err(Into::into)
    }

    // ── DCache proxy methods ─────────────��─────────────────────────────

    #[pyo3(signature = (path, backend_name, physical_path, size, entry_type, version=1, etag=None, zone_id=None, mime_type=None))]
    #[allow(clippy::too_many_arguments)]
    fn dcache_put(
        &self,
        path: &str,
        backend_name: &str,
        physical_path: &str,
        size: u64,
        entry_type: u8,
        version: u32,
        etag: Option<&str>,
        zone_id: Option<&str>,
        mime_type: Option<&str>,
    ) {
        self.inner.dcache_put(
            path,
            backend_name,
            physical_path,
            size,
            entry_type,
            version,
            etag,
            zone_id,
            mime_type,
        );
    }

    fn dcache_get(&self, path: &str) -> Option<(String, String, u8)> {
        self.inner.dcache_get(path)
    }

    fn dcache_get_full(&self, py: Python<'_>, path: &str) -> PyResult<Option<Py<PyAny>>> {
        match self.inner.dcache_get_full(path) {
            Some(e) => {
                let dict = PyDict::new(py);
                dict.set_item("backend_name", &e.backend_name)?;
                dict.set_item("physical_path", &e.physical_path)?;
                dict.set_item("size", e.size)?;
                dict.set_item("etag", e.etag.as_deref())?;
                dict.set_item("version", e.version)?;
                dict.set_item("entry_type", e.entry_type)?;
                dict.set_item("zone_id", e.zone_id.as_deref())?;
                dict.set_item("mime_type", e.mime_type.as_deref())?;
                Ok(Some(dict.into()))
            }
            None => Ok(None),
        }
    }

    fn dcache_evict(&self, path: &str) -> bool {
        self.inner.dcache_evict(path)
    }

    fn dcache_evict_prefix(&self, prefix: &str) -> usize {
        self.inner.dcache_evict_prefix(prefix)
    }

    fn dcache_contains(&self, path: &str) -> bool {
        self.inner.dcache_contains(path)
    }

    fn dcache_stats(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {
        let stats = self.inner.dcache_stats();
        let dict = PyDict::new(py);
        dict.set_item("hits", stats.hits)?;
        dict.set_item("misses", stats.misses)?;
        dict.set_item("size", stats.size)?;
        dict.set_item("hit_rate", stats.hit_rate)?;
        Ok(dict.into())
    }

    fn dcache_clear(&self) {
        self.inner.dcache_clear();
    }

    fn dcache_len(&self) -> usize {
        self.inner.dcache_len()
    }

    // ── Router proxy methods ───────────────────────────────────────────

    #[pyo3(signature = (mount_point, zone_id, readonly, admin_only, io_profile, backend_name="", local_root=None, fsync=false, py_backend=None, backend_type="cas", follow_symlinks=true, grpc_addr=None))]
    #[allow(clippy::too_many_arguments)]
    fn add_mount(
        &self,
        mount_point: &str,
        zone_id: &str,
        readonly: bool,
        admin_only: bool,
        io_profile: &str,
        backend_name: &str,
        local_root: Option<&str>,
        fsync: bool,
        py_backend: Option<Py<PyAny>>,
        backend_type: &str,
        follow_symlinks: bool,
        grpc_addr: Option<&str>,
    ) -> PyResult<()> {
        // Backend resolution: grpc_addr -> GrpcObjectStoreAdapter (zero GIL)
        //                     local_root -> CasLocalBackend/PathLocalBackend/LocalConnectorBackend
        //                     py_backend -> PyObjectStoreAdapter (GIL crossing)
        let backend: Option<Box<dyn ObjectStore>> = if backend_type == "grpc" {
            let addr = grpc_addr.ok_or_else(|| {
                pyo3::exceptions::PyValueError::new_err("grpc backend requires grpc_addr")
            })?;
            let b = crate::grpc_backend::GrpcObjectStoreAdapter::new(addr, backend_name)
                .map_err(|e| pyo3::exceptions::PyIOError::new_err(e.to_string()))?;
            Some(Box::new(b))
        } else if let Some(root) = local_root {
            if backend_type == "local_connector" {
                let b = LocalConnectorBackend::new(Path::new(root), follow_symlinks, fsync)
                    .map_err(|e| pyo3::exceptions::PyIOError::new_err(e.to_string()))?;
                Some(Box::new(b))
            } else if backend_type == "path_local" {
                let b = PathLocalBackend::new(Path::new(root), fsync)
                    .map_err(|e| pyo3::exceptions::PyIOError::new_err(e.to_string()))?;
                Some(Box::new(b))
            } else {
                let b = CasLocalBackend::new(Path::new(root), fsync)
                    .map_err(|e| pyo3::exceptions::PyIOError::new_err(e.to_string()))?;
                Some(Box::new(b))
            }
        } else {
            py_backend.map(|obj| -> Box<dyn ObjectStore> {
                Python::attach(|py| Box::new(PyObjectStoreAdapter::new(py, obj)))
            })
        };

        self.inner
            .add_mount(
                mount_point,
                zone_id,
                readonly,
                admin_only,
                io_profile,
                backend_name,
                backend,
            )
            .map_err(Into::into)
    }

    fn remove_mount(&self, mount_point: &str, zone_id: &str) -> bool {
        self.inner.remove_mount(mount_point, zone_id)
    }

    fn route(
        &self,
        path: &str,
        zone_id: &str,
        is_admin: bool,
        check_write: bool,
    ) -> PyResult<PyRustRouteResult> {
        self.inner
            .route(path, zone_id, is_admin, check_write)
            .map(Into::into)
            .map_err(Into::into)
    }

    fn has_mount(&self, mount_point: &str, zone_id: &str) -> bool {
        self.inner.has_mount(mount_point, zone_id)
    }

    fn get_mount_points(&self) -> Vec<String> {
        self.inner.get_mount_points()
    }

    // ── Trie proxy methods ─────────────────────────────────────────────

    fn trie_register(&self, pattern: &str, resolver_idx: usize) -> PyResult<()> {
        self.inner
            .trie_register(pattern, resolver_idx)
            .map_err(Into::into)
    }

    fn trie_unregister(&self, resolver_idx: usize) -> bool {
        self.inner.trie_unregister(resolver_idx)
    }

    fn trie_lookup(&self, path: &str) -> Option<usize> {
        self.inner.trie_lookup(path)
    }

    fn trie_len(&self) -> usize {
        self.inner.trie_len()
    }

    // ── Hook proxy methods ─────────────────────────────────────────────

    fn register_hook(&self, py: Python<'_>, op: &str, hook: Py<PyAny>) -> PyResult<()> {
        let hook_ref = hook.bind(py);
        let name: String = hook_ref
            .getattr("name")
            .and_then(|n| n.extract())
            .unwrap_or_else(|_| "<hook>".to_string());

        let pre_attr = format!("on_pre_{op}");
        let has_pre = hook_ref
            .getattr(pre_attr.as_str())
            .map(|attr| !attr.is_none())
            .unwrap_or(false);

        let post_attr = format!("on_post_{op}");
        let is_async_post = match hook_ref.getattr(post_attr.as_str()) {
            Ok(post_fn) => py
                .import("inspect")?
                .call_method1("iscoroutinefunction", (post_fn,))?
                .extract::<bool>()
                .unwrap_or(false),
            Err(_) => false,
        };

        let adapter = PyInterceptHookAdapter::new(py, hook.clone_ref(py));
        self.hooks
            .lock()
            .register(op, Box::new(adapter), hook, has_pre, is_async_post, name);
        Ok(())
    }

    fn unregister_hook(&self, py: Python<'_>, op: &str, hook: &Bound<'_, PyAny>) -> bool {
        self.hooks.lock().unregister(py, op, hook)
    }

    fn get_pre_hooks(&self, py: Python<'_>, op: &str) -> Vec<Py<PyAny>> {
        self.hooks.lock().get_pre_hooks(py, op)
    }

    fn get_post_hooks(&self, py: Python<'_>, op: &str) -> (Vec<Py<PyAny>>, Vec<Py<PyAny>>) {
        self.hooks.lock().get_post_hooks(py, op)
    }

    fn get_all_hooks(&self, py: Python<'_>, op: &str) -> Vec<Py<PyAny>> {
        self.hooks.lock().get_all_hooks(py, op)
    }

    fn hook_count(&self, op: &str) -> usize {
        self.hooks.lock().count(op)
    }

    // ── Observer proxy methods ─────────────────────────────────────────

    #[pyo3(signature = (obs, event_mask, is_inline=true))]
    fn register_observer(
        &self,
        py: Python<'_>,
        obs: Py<PyAny>,
        event_mask: u32,
        is_inline: bool,
    ) -> PyResult<()> {
        self.observers
            .lock()
            .register(py, obs, event_mask, is_inline)
    }

    fn unregister_observer(&self, py: Python<'_>, obs: &Bound<'_, PyAny>) -> bool {
        self.observers.lock().unregister(py, obs)
    }

    fn get_matching_observers(&self, py: Python<'_>, event_type_bit: u32) -> Vec<ObserverPair> {
        self.observers.lock().get_matching(py, event_type_bit)
    }

    /// Dispatch observers: returns (inline_observers, deferred_observers).
    /// Inline observers are meant to be awaited on the caller's path.
    /// Deferred observers are returned for Python asyncio.create_task().
    fn dispatch_observers(
        &self,
        py: Python<'_>,
        event_type_bit: u32,
    ) -> (Vec<ObserverPair>, Vec<ObserverPair>) {
        self.observers
            .lock()
            .get_matching_partitioned(py, event_type_bit)
    }

    fn observer_count(&self) -> usize {
        self.observers.lock().count()
    }

    // ── Kernel-owned observer dispatch (Phase 10) ────────────────────

    /// Register observer in pure Rust kernel registry (no GIL for filter loop).
    /// The PyMutationObserverAdapter wraps Python observers as Rust trait objects.
    #[pyo3(signature = (obs, name, event_mask, is_inline=true))]
    fn register_kernel_observer(
        &self,
        py: Python<'_>,
        obs: Py<PyAny>,
        name: &str,
        event_mask: u32,
        is_inline: bool,
    ) -> PyResult<()> {
        let adapter = PyMutationObserverAdapter { inner: obs };
        self.inner
            .register_observer(Box::new(adapter), name.to_string(), event_mask, is_inline);
        let _ = py;
        Ok(())
    }

    /// Unregister observer from kernel registry by name.
    fn unregister_kernel_observer(&self, name: &str) -> bool {
        self.inner.unregister_observer(name)
    }

    /// Dispatch inline observers in Rust (bitmask filter without GIL).
    fn dispatch_kernel_observers_inline(&self, event_type: u32, path: &str) {
        self.inner.dispatch_observers_inline(event_type, path);
    }

    /// Get count of deferred observers matching event_type.
    fn get_deferred_observer_count(&self, event_type: u32) -> usize {
        self.inner.get_deferred_observer_indices(event_type).len()
    }

    /// Total observers in kernel registry.
    fn kernel_observer_count(&self) -> usize {
        self.inner.observer_count()
    }

    // ── Hook counts ────────────────────────────────────────────────────

    fn set_hook_count(&self, op: &str, count: u64) {
        self.inner.set_hook_count(op, count);
    }

    // ── Public hook dispatch (for Tier 2 Python callers) ──────────────

    /// Dispatch pre-hooks for an operation via Rust InterceptHook trait.
    ///
    /// Called by Tier 2 Python methods (read_range, stream, write, copy, etc.)
    /// that build their own hook context objects. Tier 1 syscalls (sys_read,
    /// sys_write, etc.) dispatch pre-hooks internally.
    #[pyo3(signature = (op, hook_ctx))]
    fn dispatch_pre_hooks(&self, op: &str, hook_ctx: Py<PyAny>) -> PyResult<()> {
        if !self.inner.has_hooks(op) {
            return Ok(());
        }
        let hooks = self.hooks.lock();
        let impls = hooks.get_pre_hook_impls(op);
        for hook in impls {
            match op {
                "read" => hook.on_pre_read(&hook_ctx)?,
                "write" => hook.on_pre_write(&hook_ctx)?,
                "delete" => hook.on_pre_delete(&hook_ctx)?,
                "rename" => hook.on_pre_rename(&hook_ctx)?,
                "mkdir" => hook.on_pre_mkdir(&hook_ctx)?,
                "rmdir" => hook.on_pre_rmdir(&hook_ctx)?,
                "copy" => hook.on_pre_copy(&hook_ctx)?,
                "stat" => hook.on_pre_stat(&hook_ctx)?,
                "access" => hook.on_pre_access(&hook_ctx)?,
                "write_batch" => hook.on_pre_write_batch(&hook_ctx)?,
                _ => {}
            }
        }
        Ok(())
    }

    // ── Post-hook dispatch (sync Rust + return async for Python) ───────���

    /// Dispatch post-hooks: sync in Rust, return async hooks for Python.
    ///
    /// Sync post-hooks: serial, fault-isolated (fire-and-forget).
    /// Returns async hooks as Vec<Py<PyAny>> for Python asyncio.gather.
    #[pyo3(signature = (op, hook_ctx))]
    fn dispatch_post_hooks(
        &self,
        py: Python<'_>,
        op: &str,
        hook_ctx: Py<PyAny>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        if !self.inner.has_hooks(op) {
            return Ok(Vec::new());
        }
        // 1. Dispatch sync post-hooks in Rust (fire-and-forget)
        self.dispatch_post_hooks_sync(op, &hook_ctx);

        // 2. Return async hooks for Python to schedule
        let hooks = self.hooks.lock();
        let (_, async_hooks) = hooks.get_post_hooks(py, op);
        Ok(async_hooks)
    }

    // ── sys_read ───────────────────────────────────────────────────────

    #[pyo3(signature = (path, ctx))]
    fn sys_read<'py>(
        &self,
        py: Python<'py>,
        path: &str,
        ctx: &PyOperationContext,
    ) -> PyResult<PySysReadResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("read") {
            // Convert Rust ctx to Python OperationContext dataclass (full round-trip)
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let rhc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("ReadHookContext")?
                .call1((path, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("read", &rhc)?;
        }

        // 2. Call pure Rust kernel (releasing GIL for VFS lock blocking)
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner.sys_read(path, &rust_ctx));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        // 3. Convert Vec<u8> -> PyBytes
        Ok(PySysReadResult {
            hit: result.hit,
            data: result.data.map(|d| PyBytes::new(py, &d).into()),
            post_hook_needed: result.post_hook_needed,
            content_hash: result.content_hash,
            entry_type: result.entry_type,
        })
    }

    // ── sys_write ──────────────────────────────────────────────────────

    #[pyo3(signature = (path, ctx, content))]
    fn sys_write<'py>(
        &self,
        py: Python<'py>,
        path: &str,
        ctx: &PyOperationContext,
        content: &[u8],
    ) -> PyResult<PySysWriteResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("write") {
            // Convert Rust ctx to Python OperationContext dataclass (full round-trip)
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let whc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("WriteHookContext")?
                .call1((path, content, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("write", &whc)?;
        }

        // 2. Call pure Rust kernel (releasing GIL for VFS lock blocking)
        let rust_ctx = ctx.to_rust();
        let content_owned = content.to_vec();
        let result = py.detach(|| self.inner.sys_write(path, &rust_ctx, &content_owned));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        Ok(PySysWriteResult {
            hit: result.hit,
            content_id: result.content_id,
            post_hook_needed: result.post_hook_needed,
            version: result.version,
            size: result.size,
        })
    }

    // ── sys_stat ───────────────────────────────────────────────────────

    fn sys_stat<'py>(
        &self,
        py: Python<'py>,
        path: &str,
        zone_id: &str,
        is_admin: bool,
    ) -> PyResult<Option<Bound<'py, PyDict>>> {
        match self.inner.sys_stat(path, zone_id, is_admin) {
            Some(s) => {
                let dict = PyDict::new(py);
                dict.set_item("path", &s.path)?;
                dict.set_item("backend_name", &s.backend_name)?;
                dict.set_item("physical_path", &s.physical_path)?;
                dict.set_item("size", s.size)?;
                dict.set_item("etag", s.etag.as_deref())?;
                dict.set_item("mime_type", &s.mime_type)?;
                dict.set_item("created_at", py.None())?;
                dict.set_item("modified_at", py.None())?;
                dict.set_item("is_directory", s.is_directory)?;
                dict.set_item("entry_type", s.entry_type)?;
                dict.set_item("mode", s.mode)?;
                dict.set_item("version", s.version)?;
                dict.set_item("zone_id", s.zone_id.as_deref())?;
                Ok(Some(dict))
            }
            None => Ok(None),
        }
    }

    // ── sys_unlink ────────────────────────────────────────────────────

    #[pyo3(signature = (path, ctx))]
    fn sys_unlink(
        &self,
        py: Python<'_>,
        path: &str,
        ctx: &PyOperationContext,
    ) -> PyResult<PySysUnlinkResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("delete") {
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let dhc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("DeleteHookContext")?
                .call1((path, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("delete", &dhc)?;
        }

        // 2. Call pure Rust kernel
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner.sys_unlink(path, &rust_ctx));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        Ok(PySysUnlinkResult {
            hit: result.hit,
            entry_type: result.entry_type,
            post_hook_needed: result.post_hook_needed,
            path: result.path,
            etag: result.etag,
            size: result.size,
        })
    }

    // ── sys_rename ────────────────────────────────────────────────────

    #[pyo3(signature = (old_path, new_path, ctx))]
    fn sys_rename(
        &self,
        py: Python<'_>,
        old_path: &str,
        new_path: &str,
        ctx: &PyOperationContext,
    ) -> PyResult<PySysRenameResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("rename") {
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let rhc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("RenameHookContext")?
                .call1((old_path, new_path, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("rename", &rhc)?;
        }

        // 2. Call pure Rust kernel
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner.sys_rename(old_path, new_path, &rust_ctx));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        Ok(PySysRenameResult {
            hit: result.hit,
            success: result.success,
            post_hook_needed: result.post_hook_needed,
            is_directory: result.is_directory,
        })
    }

    // ── sys_mkdir ─────────────────────────────────────────────────────

    #[pyo3(signature = (path, ctx, parents=true, exist_ok=true))]
    fn sys_mkdir(
        &self,
        py: Python<'_>,
        path: &str,
        ctx: &PyOperationContext,
        parents: bool,
        exist_ok: bool,
    ) -> PyResult<PySysMkdirResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("mkdir") {
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let mhc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("MkdirHookContext")?
                .call1((path, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("mkdir", &mhc)?;
        }

        // 2. Call pure Rust kernel (full mkdir)
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner.sys_mkdir(path, &rust_ctx, parents, exist_ok));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        Ok(PySysMkdirResult {
            hit: result.hit,
            post_hook_needed: result.post_hook_needed,
        })
    }

    // ── sys_rmdir ─────────────────────────────────────────────────────

    #[pyo3(signature = (path, ctx, recursive=false))]
    fn sys_rmdir(
        &self,
        py: Python<'_>,
        path: &str,
        ctx: &PyOperationContext,
        recursive: bool,
    ) -> PyResult<PySysRmdirResult> {
        // 1. PRE-INTERCEPT hooks (GIL, abort on exception)
        if self.inner.has_hooks("rmdir") {
            let py_ctx = rust_ctx_to_python(py, &ctx.to_rust(), "")
                .map_err(pyo3::exceptions::PyRuntimeError::new_err)?;
            let rhc = py
                .import("nexus.contracts.vfs_hooks")?
                .getattr("RmdirHookContext")?
                .call1((path, py_ctx))?
                .unbind();
            self.dispatch_pre_hooks_inner("rmdir", &rhc)?;
        }

        // 2. Call pure Rust kernel (full rmdir)
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner.sys_rmdir(path, &rust_ctx, recursive));
        let result = result.map_err(|e| -> PyErr { e.into() })?;

        Ok(PySysRmdirResult {
            hit: result.hit,
            post_hook_needed: result.post_hook_needed,
            children_deleted: result.children_deleted,
        })
    }

    // ── Tier 2 convenience methods ────────────────────────────────────

    #[pyo3(signature = (path, zone_id, is_admin))]
    fn access(&self, path: &str, zone_id: &str, is_admin: bool) -> bool {
        self.inner.access(path, zone_id, is_admin)
    }

    #[pyo3(signature = (parent_path, zone_id, is_admin))]
    fn readdir(&self, parent_path: &str, zone_id: &str, is_admin: bool) -> Vec<(String, u8)> {
        self.inner.readdir(parent_path, zone_id, is_admin)
    }

    // ── Internal batch functions ──────────────────────────────────────

    /// Batch write: validate + route + lock + write + metastore + dcache.
    /// Returns list of SysWriteResult (one per item).
    #[pyo3(signature = (items, ctx))]
    fn _write_batch<'py>(
        &self,
        py: Python<'py>,
        items: Vec<(String, Vec<u8>)>,
        ctx: &PyOperationContext,
    ) -> PyResult<Vec<PySysWriteResult>> {
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner._write_batch(&items, &rust_ctx));
        let results = result.map_err(|e| -> PyErr { e.into() })?;
        Ok(results
            .into_iter()
            .map(|r| PySysWriteResult {
                hit: r.hit,
                content_id: r.content_id,
                post_hook_needed: r.post_hook_needed,
                version: r.version,
                size: r.size,
            })
            .collect())
    }

    /// Batch read: loops sys_read for each path.
    /// Returns list of SysReadResult (one per path).
    #[pyo3(signature = (paths, ctx))]
    fn _read_batch<'py>(
        &self,
        py: Python<'py>,
        paths: Vec<String>,
        ctx: &PyOperationContext,
    ) -> PyResult<Vec<PySysReadResult>> {
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner._read_batch(&paths, &rust_ctx));
        let results = result.map_err(|e| -> PyErr { e.into() })?;
        Ok(results
            .into_iter()
            .map(|r| PySysReadResult {
                hit: r.hit,
                data: r
                    .data
                    .map(|d| Python::attach(|py| PyBytes::new(py, &d).into())),
                post_hook_needed: r.post_hook_needed,
                content_hash: r.content_hash,
                entry_type: r.entry_type,
            })
            .collect())
    }

    /// Batch delete: loops sys_unlink for each path.
    /// Returns list of SysUnlinkResult (one per path).
    #[pyo3(signature = (paths, ctx))]
    fn _delete_batch(
        &self,
        py: Python<'_>,
        paths: Vec<String>,
        ctx: &PyOperationContext,
    ) -> PyResult<Vec<PySysUnlinkResult>> {
        let rust_ctx = ctx.to_rust();
        let result = py.detach(|| self.inner._delete_batch(&paths, &rust_ctx));
        let results = result.map_err(|e| -> PyErr { e.into() })?;
        Ok(results
            .into_iter()
            .map(|r| PySysUnlinkResult {
                hit: r.hit,
                entry_type: r.entry_type,
                post_hook_needed: r.post_hook_needed,
                path: r.path,
                etag: r.etag,
                size: r.size,
            })
            .collect())
    }
}

// ── Private: hook dispatch (wrapper-only) ───────────────────────────────

impl PyKernel {
    /// Internal pre-hook dispatch (used by Tier 1 syscalls).
    fn dispatch_pre_hooks_inner(&self, op: &str, hook_ctx: &Py<PyAny>) -> PyResult<()> {
        let hooks = self.hooks.lock();
        let impls = hooks.get_pre_hook_impls(op);
        for hook in impls {
            match op {
                "read" => hook.on_pre_read(hook_ctx)?,
                "write" => hook.on_pre_write(hook_ctx)?,
                "delete" => hook.on_pre_delete(hook_ctx)?,
                "rename" => hook.on_pre_rename(hook_ctx)?,
                "mkdir" => hook.on_pre_mkdir(hook_ctx)?,
                "rmdir" => hook.on_pre_rmdir(hook_ctx)?,
                "copy" => hook.on_pre_copy(hook_ctx)?,
                "stat" => hook.on_pre_stat(hook_ctx)?,
                "access" => hook.on_pre_access(hook_ctx)?,
                "write_batch" => hook.on_pre_write_batch(hook_ctx)?,
                _ => {}
            }
        }
        Ok(())
    }

    /// Dispatch sync post-hooks via Rust InterceptHook trait.
    ///
    /// Runs sync post-hooks serially, fault-isolated (fire-and-forget).
    /// Async hooks are NOT handled here — Python thin wrapper schedules
    /// them via asyncio.gather (codegen or manual).
    fn dispatch_post_hooks_sync(&self, op: &str, hook_ctx: &Py<PyAny>) {
        let hooks = self.hooks.lock();
        let impls = hooks.get_post_hook_impls(op);
        for hook in impls {
            match op {
                "read" => hook.on_post_read(hook_ctx),
                "write" => hook.on_post_write(hook_ctx),
                "delete" => hook.on_post_delete(hook_ctx),
                "rename" => hook.on_post_rename(hook_ctx),
                "mkdir" => hook.on_post_mkdir(hook_ctx),
                "rmdir" => hook.on_post_rmdir(hook_ctx),
                "copy" => hook.on_post_copy(hook_ctx),
                "stat" => hook.on_post_stat(hook_ctx),
                "access" => hook.on_post_access(hook_ctx),
                "write_batch" => hook.on_post_write_batch(hook_ctx),
                _ => {}
            }
        }
    }
}
