//! Metastore pillar — Rust kernel metadata contract.
//!
//! Rust equivalent of Python `MetastoreABC` (one of the Four Storage Pillars).
//! Provides ordered key-value storage for file metadata (inodes, config, topology).
//!
//! Local impl: RedbMetastore (redb crate, ~5μs reads).
//! Remote impl: gRPC client (existing network boundary).
//!
//! Issue #1868: Pure Rust ABI — no PyO3 dependency.
//! PyMetastoreAdapter lives in generated_adapters.rs (auto-generated).

/// Metadata record for a single file/directory.
///
/// Mirrors the Python `FileMetadata` fields needed by the Rust kernel.
#[derive(Clone, Debug)]
#[allow(dead_code)]
pub(crate) struct FileMetadata {
    pub(crate) path: String,
    pub(crate) backend_name: String,
    pub(crate) physical_path: String,
    pub(crate) size: u64,
    pub(crate) etag: Option<String>,
    pub(crate) version: u32,
    pub(crate) entry_type: u8,
    pub(crate) zone_id: Option<String>,
    pub(crate) mime_type: Option<String>,
}

/// Error type for Metastore operations.
#[derive(Debug)]
#[allow(dead_code)]
pub(crate) enum MetastoreError {
    /// Key not found.
    NotFound(String),
    /// Underlying I/O or storage error.
    IOError(String),
}

/// Metastore pillar — kernel metadata contract.
///
/// Rust equivalent of Python `MetastoreABC`.
/// Local impls (redb) implement directly; remote impls go through
/// existing gRPC network boundaries.
///
/// 5 abstract methods matching the Python ABC:
///   - get, put, delete, list, exists
#[allow(dead_code)]
pub(crate) trait Metastore: Send + Sync {
    /// Get metadata for a path. Returns None if not found.
    fn get(&self, path: &str) -> Result<Option<FileMetadata>, MetastoreError>;

    /// Put metadata at a path (insert or update).
    fn put(&self, path: &str, metadata: FileMetadata) -> Result<(), MetastoreError>;

    /// Delete metadata at a path. Returns true if it existed.
    fn delete(&self, path: &str) -> Result<bool, MetastoreError>;

    /// List all metadata entries under a prefix.
    fn list(&self, prefix: &str) -> Result<Vec<FileMetadata>, MetastoreError>;

    /// Check if a path exists in the metastore.
    fn exists(&self, path: &str) -> Result<bool, MetastoreError>;
}

// PyMetastoreAdapter + conversion helpers (extract_metadata, to_python_metadata)
// are in generated_adapters.rs — auto-generated by scripts/codegen_kernel_abi.py.
// This file stays language-agnostic (pure Rust ABI).
