"""API v2 routers."""

from nexus.server.api.v2.routers import (
    bricks,
    conflicts,
    connectors,
    consolidation,
    curate,
    events_replay,
    eviction,
    feedback,
    memories,
    mobile_search,
    operations,
    pay,
    playbooks,
    reflect,
    reputation,
    sync_push,
    trajectories,
    workflows,
)

__all__ = [
    "bricks",
    "conflicts",
    "connectors",
    "consolidation",
    "curate",
    "events_replay",
    "feedback",
    "memories",
    "mobile_search",
    "operations",
    "pay",
    "playbooks",
    "reflect",
    "reputation",
    "sync_push",
    "trajectories",
    "workflows",
]
